import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          //drawer
          'changepassword': 'Change Password',
          'biometric': 'Biometric',
          'languages': 'Languages',
          'privacyPolicy': 'Privacy Policy',
          'termsAndConditions': 'Terms & Conditions',
          'deleteAccount': 'Delete Account',
          'logout': 'Logout',
          //Dashboard
          'goodmorning': "G o o d  M o r n i n g",
          'goodEvening': 'G o o d  E v e n i n g',
          'goodNight': 'G o o d  N i g h t',
          'goodAfterNoon': 'G o o d  A f t e r n o o n',
          'hi': 'Hi,',
          'todayappointments': 'Today \nAppointments',
          'appointmenthistory': 'Appointment \nHistory',
          'registrationordering': 'Registration \n& Ordering',
          'comingsoon': 'Coming \nSoon',
          'registration': 'Registration',
          'registerpatient': 'Registered Patient',
          //profile
          'profile': 'Profile',
          'vehiclenumber': 'Vehicle Number',
          'govid': 'Government ID',
          'contact': 'Contact No',
          'dob': 'Date of Birth',
          'address': 'Address',
          //changepassword
          'welcometo': 'Welcome To',
          'helpful': 'Helpful.',
          'oldpassword': 'Enter Old Password',
          'newpassword': 'Enter New Password',
          'confirmpassword': 'Confirm New Password',
          'submit': 'Submit',
          'pleaseoldpassword': "Please enter old password",
          'pleasenewpassword': 'Please enter new password',
          'pleaseconfirmpassword': 'Please confirm new password',
          'passwordnotmatch': 'Passwords do not match',
          'passwordsuccess': 'Password changed successfully',
          'passwordfailed': 'Old Password is wrong',
          //notification
          'notification': 'Notification',
          //appointments
          'todayappointment': 'Today Appointments',
          'appointmenhistory': 'Appointment History',
          'from': 'From',
          'to': 'To',
          'test': 'Test  |',
          'addres': 'Address  |',
          'viewinformation':'View Information',
          'startride':'Start Ride',
          'ridestatus':'Ride Status',
          'wanttostart':'Do you want to start Ride?',
          'ridestarted':'Ride Started Succefully!',
          'yes':'Yes',
          'no':'No',
          'cancel':'Cancel',
          'arrived':'Arrived',
          'cancelride':'Cancel Ride',
          'remarks':'Remarks',
          'enterremarks':'Enter Remarks',
          'pleaseenterremarks':"Please Enter Remarks First",
          'pleaseselect':"Please Select Lab",
          'ok':'OK',
          'arrivedatlocation':'Are You Arrived at Patient Location?',
          'checkin':'Check In',
          'paymentmethod':'   Payment Method',
          'discount':'Discount:',
          'paymentstatus':'Payment Status:',
          'totalamount':'Total Amount:',
          'percentage':"Percentage",
          'amount':'Amount',
          'samplecollected':'Sample Collected',
          'inroutelab':'In Route to Lab',
          'selectlab':'Select Lab',
          'deliversample':'Deliver Sample',
          'ridecompleted':'Ride Completed',
          'thankyou':'Thank You',
          'backhome':'BACK HOME',
          'order':'Order:',

          //Registration
          'fullname': 'Full Name',
          'email': 'Email',
          'gender': 'Gender',
          'country': 'Country',
          'state': 'State',
          'city': 'City',
          'relation': 'Relation',
          'nationalid': 'National ID 123-4567-8910111-2',
          'entername': 'Enter your full name',
          'entervalidno': 'Please enter a valid number',
          'enteremail': 'Enter Your Email',
          'selectgender': 'Please select a gender',
          'enterid': 'Enter ID Number',
          'enteraddress': 'Enter Your Address',
          
        },
        "ar_SA": {
          //drawer
          'changepassword': 'تغيير كلمة المرور',
          'biometric': 'بصمات',
          'languages': 'اللغات',
          'privacyPolicy': 'سياسة الخصوصية',
          'termsAndConditions': 'البنود و الظروف',
          'deleteAccount': 'حذف الحساب',
          'logout': 'تسجيل خروج',
          //Dashboard
          'goodmorning': "صباح الخير",
          'goodEvening': 'مساء الخير',
          'goodNight': 'طاب مساؤك',
          'goodAfterNoon': 'مساء الخير',
          'hi': 'أهلاً,',
          'todayappointments': 'مواعيد اليوم',
          'appointmenthistory': 'تاريخ التعيين',
          'registrationordering': 'التسجيل والطلب',
          'comingsoon': 'قريباً',
          'registration': 'تسجيل',
          'registerpatient': 'مريض مسجل',
          //profile
          'vehiclenumber': 'عدد المركبات',
          'govid': 'معرف الحكومة',
          'contact': 'رقم الاتصال',
          'dob': 'تاريخ الميلاد',
          'address': 'عنوان',
          'profile': 'حساب تعريفي',
          //changepassword
          'welcometo': 'مرحبا بك في',
          'helpful': 'Helpful.',
          'oldpassword': 'أدخل كلمة المرور القديمة',
          'newpassword': 'أدخل كلمة المرور الجديدة',
          'confirmpassword': 'تأكيد كلمة المرور الجديدة',
          'submit': 'يُقدِّم',
          'pleaseoldpassword': "الرجاء إدخال كلمة المرور القديمة",
          'pleasenewpassword': 'الرجاء إدخال كلمة المرور الجديدة',
          'pleaseconfirmpassword': 'كلمة المرور غير متطابقة',
          'passwordnotmatch': 'كلمة المرور غير متطابقة',
          'passwordsuccess': 'تم تغيير كلمة المرور بنجاح',
          'passwordfailed': 'كلمة المرور القديمة خاطئة',
          //Notification
          'notification': 'إشعار',
          //appointments
          'todayappointment': 'مواعيد اليوم',
          'appointmenhistory': 'تاريخ التعيين',
          'from': 'من',
          'to': 'إلى',
          'test': 'امتحان   | ',
          'addres': 'عنوان   | ',
           'viewinformation':'عرض المعلومات',
           'startride':'ابدأ الركوب',
            'ridestatus':'حالة الركوب',
          'wanttostart':'هل تريد أن تبدأ الركوب',
          'yes':'نعم',
          'no':'لا',
          'cancel':'يلغي',
          'arrived':'وصل',
          'cancelride':'إلغاء الرحلة',
          'remarks':'ملاحظات',
          'enterremarks':'أدخل الملاحظات',
          'ok':'تمام',
          'arrivedatlocation':'هل وصلت إلى موقع المريض',
          'checkin':'تحقق في',
          'paymentmethod':'طريقة الدفع او السداد',
          'discount':'تخفيض:',
          'paymentstatus':'حالة السداد:',
          'totalamount':'المبلغ الإجمالي:',
          'percentage':'نسبة مئوية',
          'amount':'كمية',
          'samplecollected':'العينة التي تم جمعها',
          'inroutelab':'في الطريق إلى المختبر',
          'selectlab':'حدد المختبر',
          'deliversample':'تسليم العينة',
          'ridecompleted':'اكتملت الرحلة',
          'thankyou':'شكرًا لك',
          'backhome':'العودة إلى المنزل',
          'order':'طلب:',
          'ridestarted':'بدأت الرحلة بنجاح!',
          'pleaseselect':"الرجاء اختيار المختبر",

          //Registration
          'fullname': 'الاسم الكامل',
          'email': 'البريد الإلكتروني',
          'gender': 'الجنس',
          'country': 'البلد',
          'state': 'الولاية',
          'city': 'المدينة',
          'relation': 'علاقة',
          'nationalid': 'الهوية الوطنية 123-4567-8910111-2',
          'entername': 'أدخل اسمك الكامل',
          'entervalidno': 'من فضلك أدخل رقما صالحا',
          'enteremail': 'أدخل بريدك الإلكتروني',
          'selectgender': 'الرجاء تحديد الجنس',
          'enterid': 'أدخل رقم الهوية',
          'enteraddress': 'أدخل عنوانك',
        },
        "ur_PK": {
          //drawer
          'changepassword': 'تغيير كلمة المرور',
          'biometric': 'بائیو میٹرک',
          'languages': 'زبانیں',
          'privacyPolicy': 'رازداری اور پالیسی',
          'termsAndConditions': 'شرائط و ضوابط',
          'deleteAccount': 'کھاتہ مٹا دو',
          'logout': 'لاگ آوٹ',
          //Dashboard
          'goodmorning': "صبح بخیر",
          'goodEvening': 'شام بخیر',
          'goodNight': 'شب بخیر',
          'goodAfterNoon': 'دوپہر بخیر',
          'hi': 'ہیلو,',
          'todayappointments': 'آج کی ملاقاتیں',
          'appointmenthistory': 'تقرری کی تاریخ',
          'registrationordering': 'رجسٹریشن اور آرڈر',
          'comingsoon': 'جلد آرہا ہے',
          'registration': 'اندراج',
          'registerpatient': 'رجسٹرڈ مریض',
          //profile
          'profile': 'پروفائل',
          'vehiclenumber': 'گاڑی کا نمبر',
          'govid': 'سرکاری آئی ڈی',
          'contact': 'رابطہ نمبر',
          'dob': 'پیدائش کی تاریخ',
          'address': 'پتہ',
          //changepassword
          'welcometo': 'خوش آمدید',
          'helpful': 'Helpful.',
          'oldpassword': 'پرانا پاس ورڈ درج کریں',
          'newpassword': 'نیا پاس ورڈ درج کریں',
          'confirmpassword': 'نئے پاس ورڈ کی توثیق کریں',
          'submit': 'جمع کرائیں',
          'pleaseoldpassword': "براہ کرم پرانا پاس ورڈ درج کریں",
          'pleasenewpassword': 'براہ کرم نیا پاس ورڈ درج کریں',
          'pleaseconfirmpassword': 'براہ کرم تصدیقی پاس ورڈ درج کریں',
          'passwordnotmatch': 'پاس ورڈز مماثل نہیں ہیں',
          'passwordsuccess': 'پاس ورڈ کامیابی سے تبدیل کر دیا گیا',
          'passwordfailed': 'پرانا پاس ورڈ غلط ہے',
          //Notification
          'notification': 'اطلاع',
          //appointments
          'todayappointment': 'آج کی ملاقاتیں',
          'appointmenhistory': 'تقرری کی تاریخ',
          'from': 'سے',
          'to': 'تک',
          'test': 'ٹیسٹ   | ',
          'addres': 'پتہ   | ',
           'viewinformation':'معلومات دیکھیں',
           'startride':'سواری شروع کریں',
            'ridestatus':'سواری کی حالت',
          'wanttostart':'کیا آپ سواری شروع کرنا چاہتے ہیں؟',
          'yes':'جی ہاں',
          'no':'نہیں',
          'cancel':'منسوخ کریں',
          'arrived':'پہنچ گئے',
          'cancelride':'سواری منسوخ کریں',
          'remarks':'ریمارکس',
          'enterremarks':'ریمارکس درج کریں',
          'ok':'ٹھیک ہے',
          'arrivedatlocation':'کیا آپ مریض کے مقام پر پہنچ گئے ہیں؟',
          'checkin':'چیک ان',
          'paymentmethod':'ادائیگی کا طریقہ',
          'discount':'رعایت:',
          'paymentstatus':'ادائیگی کی حیثیت:',
          'totalamount':'کل رقم:',
          'percentage':"فیصد",
          'amount':'رقم',
          'samplecollected':'نمونہ جمع ',
          'inroutelab':'لیبارٹری کے راستے میں',
          'selectlab':'لیبارٹری کو منتخب کریں',
          'deliversample':'نمونہ فراہم کریں',
          'ridecompleted':'سواری مکمل',
          'thankyou':'شکریہ',
          'backhome':'واپس ڈیش بورڈ',
          'order':'ترتیب:',
          'ridestarted':'سواری کامیابی سے شروع ہوچکی ہے!',
          'pleaseselect':"براہ کرم لیب کو منتخب کریں",

          //Registration
          'fullname': 'پورا نام',
          'email': 'ای میل',
          'gender': 'جنس',
          'country': 'ملک',
          'state': 'صوبہ',
          'city': 'شہر',
          'relation': 'رشتہ',
          'nationalid': 'قومی شناخت  123-4567-8910111-2',
          'entername': 'اپنا پورا نام درج کریں',
          'entervalidno': 'براہ مہربانی ایک درست نمبر درج کریں',
          'enteremail': 'اپنا ای میل درج کریں',
          'selectgender': 'براہ کرم ایک جنس منتخب کریں',
          'enterid': 'شناختی نمبر درج کریں',
          'enteraddress': 'اپنا پتہ درج کریں',
        }
      };
}
// "welcometo": "مرحبا بك في",
//           "takecareof": "اعتني ب ",
//           "yourhealth": "صحتك!",
//           "with": "مع",
//           'goodmorning': "صباح الخير",
//           'goodEvening': 'مساء الخير',
//           'goodNight': 'طاب مساؤك',
//           'goodAfterNoon': 'مساء الخير',
//           'onlineOffline': 'متصل غير متصل',
//           'consultations': 'استشارات',
//           'booknow': 'احجز الآن',
//           'selectservices': 'حدد الخدمات',
//           'homeSample': 'عينة المنزل',
//           'imageBooking': 'حجز الصور',
//           'doctorConsultation': 'استشارة الطبيب',
//           'reports': 'التقارير',
//           'healthSummary': 'ملخص الصحة',
//           'healthAnalysis': 'التحليل الصحي',
//           'todayAvailable': 'متوفر اليوم',
//           'generalConsultation': 'الاستشارة العامة',
//           'getAppointment': 'احصل على موعد',
//           'home': 'بيت',
//           'profile': 'حساب تعريفي',
//           'schedule': 'جدول',
//           'help': 'يساعد',
//           'history': 'تاريخ',
//           'familyMembers': 'أفراد الأسرة',
//           'location': 'موقع',
//           'wallet': 'محفظة',
//           'packages': 'الحزم',
//           'forgotPassword': 'هل نسيت كلمة السر',
//           'biometric': 'بصمات',
//           'privacyPolicy': 'سياسة الخصوصية',
//           'termsAndConditions': 'البنود و الظروف',
//           'logout': 'تسجيل خروج',
//           'labInvestions': 'التحقيقات المخبرية',
//           'selectTest': 'حدد اختبار',
//           'description': 'وصف',
//           'address': 'عنوان',
//           'paymentMethod': 'طريقة الدفع او السداد',
//           'prescribedBy': 'المنصوص عليها',
//           'self': 'الذات',
//           'doctor': 'طبيب',
//           'outdoorDoctor': 'طبيب خارجي',
//           'select Doctor': 'اختر الطبيب',
//           'summary': 'ملخص',
//           'datehour': 'التاريخ والساعة',
//           'package': 'طَرد',
//           'test': 'امتحان',
//           'price': 'سعر',
//           'grandTotal': 'المجموع الإجمالي',
//           'appointmentConfirm': 'موعد الكتاب',
//           'attachPrescription': 'إرفاق وصفة طبية',
//           'login': 'تسجيل الدخول',
//           'Login': 'تسجيل الدخول',
//           'donthaveanAccount': 'لا تملك حساب',
//           'register': 'يسجل',
//           'registerNow': 'سجل الان',
//           'fullName': 'الاسم الكامل',
//           'yourMobNumber': 'رقم هاتفك',
//           'email': 'بريد إلكتروني',
//           'dateOfBirth': 'تاريخ الميلاد',
//           'gender': 'جنس',
//           'password': 'كلمة المرور',
//           'retypePassword': 'أعد إدخال كلمة السر',
//           'country': 'دولة',
//           'state': 'ولاية',
//           'city': 'مدينة',
//           'street': 'شارع',
//           'alreadyHaveAnAccount': 'هل لديك حساب؟',
//           'signin': 'تسجيل الدخول',
//           'registered': 'مسجل',
//           'registrationCompleted': 'تم التسجيل بنجاح',
//           'ok': 'نعم',
//           'payfromYourWallet': 'ادفع من محفظتك',
//           'payOnline': 'ادفع عبر الإنترنت',
//           'payAtClinic': 'الدفع في العيادة',
//           'congratulations': 'تهانينا',
//           'myAppointments': 'مواعيدي',
//           'bookyourAppointments': 'احجز موعدك',
//           'searchDoctor': 'البحث عن الأطباء',
//           'patients': "مرضى",
//           'yearExperience': 'سنوات من الخبرة',
//           'rating': 'التقييمات',
//           'reviews': 'التعليقات',
//           'descriptions': 'الأوصاف',
//           'workingTime': 'وقت العمل',
//           'online&Clinic': 'رسوم الاستشارة عبر الإنترنت والعيادة',
//           'bookAppointment': 'موعد الكتاب',
//           'welcomeTo': 'مرحبا بك في',
//           'username': 'اسم المستخدم',
//           'oopsFailed': 'عفوًا، فشل',
//           'appointmentFailed': 'فشل الموعد',
//           'checkInternet': 'الرجاء التحقق من اتصالك بالإنترنت وحاول مرة أخرى',
//           'appointmentBooked': 'تم حجز الموعد بنجاح',
//           'viewAppointment': 'عرض الموعد',
//           'cancel': 'يلغي',
//           'glucose': "الجلوكوز",
//           'bloodPressure': 'ضغط الدم',
//           'measurements': 'قياسات',
//           'connect': 'يتصل',
//           'pulse': 'نبض',
//           'temperature': 'درجة حرارة',
//           'labTestResult': 'نتيجة الاختبار المعملي',
//           'status': 'حالة',
//           'pending': 'قيد الانتظار',
//           'allergies': 'الحساسية',
//           'addGlucose': 'أضف الجلوكوز',
//           'normal': 'طبيعي',
//           'fasting': 'صيام',
//           'values': 'قيم',
//           'condtition': 'حالة',
//           'saveRecord': 'حفظ السجل',
//           'calculate': 'احسب',
//           'bmiCalculator': 'حاسبة مؤشر كتلة الجسم',
//           'BMI': 'مؤشر كتلة الجسم',
//           'glucoseLevelMonitor': 'مراقب مستوى الجلوكوز',
//           'enterValue': 'أدخل القيمة',
//           'collectLocationData':
//               'يقوم طبيب البيت لرعاية المرضى بجمع بيانات الموقع لتمكين خدمات أخذ العينات المنزلية حتى عندما تكون مغلقة أو غير مستخدمة',
//           'permissions': 'الأذونات',
//           'deleteAccount': 'حذف الحساب',
//           'languages': "لغة",
//           'identityNumber': 'رقم الهوية',
//           'signup': 'اشتراك',
//           'bpm': 'نبضة في الدقيقة',
//           'date': 'تاريخ',
//           'time': 'وقت',
//           'searchForSpecialities': 'البحث عن القسم',
//           'consultNow': 'استشر عبر الإنترنت',
//           'specialists': 'المتخصصين',
//           'upcomingAppointments': 'المواعيد القادمة',
//           'dateAndTime': 'التاريخ و الوقت',
//           'reschedule': 'إعادة جدولة',
//           'onlineConsultation': 'التشاور عبر الإنترنت',
//           'information1':
//               'يستهدف نظامنا وتطبيقاتنا بشكل أساسي الرعاية الصحية والطبية. نقوم بجمع بعض المعلومات والأذونات الأخرى في تطبيقاتنا لتحسين تجربة المستخدم ووظائف التطبيق. تتم معالجة المعلومات التي نجمعها بشكل مؤقت، أي أنها تستخدم فقط لبدء بعض الخدمات أو الوظائف الموجودة داخل التطبيق ولا يتم استخدامها بعد إيقافها. تم ذكر بعض الأمور المهمة أدناه مع الإفصاح/أسباب التجميع البارزة',
//           'information2':
//               'الموقع: لإظهار الأطباء القريبين، يحتاج التطبيق إلى الحصول على هذا الإذن من المستخدم. من خلال تمكين الخدمات المستندة إلى الموقع على جهازك، فإنك توافق وتقر بأن (أ) بيانات الجهاز التي يتم جمعها منك ذات صلة مباشرة باستخدامك للتطبيق، (ب) قد نقدم خدمات تعتمد على الموقع تتعلق وتستند إلى موقعك الحالي في ذلك الوقت، و (ج) يجوز لنا استخدام أي معلومات تم جمعها فيما يتعلق بتوفير التطبيق. لإجراء مكالمات فيديو بين الطبيب والمريض. لإجراء مكالمات صوتية بين الطبيب والمريض (أ) يمكن للمستخدم/المريض تحميل صورة الملف الشخصي (ب) يمكن للمستخدم/المريض تحميل السجلات والملفات الصحية ليقوم الطبيب بفحصها (ج) يمكن للمستخدم/المريض تنزيل وعرض التقارير وما إلى ذلك.',
//           'usage':
//               'نحن نستخدم المعلومات التي نجمعها بطرق مختلفة، بما في ذلك: (أ) توفير خدماتنا ومنتجاتنا وتشغيلها وصيانتها (ب) فهم وتحليل كيفية استخدامك لخدماتنا ومنتجاتنا (ج) تطوير منتج جديد وميزات الخدمات و الوظيفة (د) التواصل معك، إما بشكل مباشر أو من خلال أحد شركائنا، بما في ذلك خدمة العملاء، لتزويدك بالتحديثات والمعلومات الأخرى المتعلقة بالموقع، ولأغراض تسويقية وترويجية (هـ) إرسال رسائل البريد الإلكتروني الخاصة بك (و) البحث عن الاحتيال ومنعه',
//           'disclosure':
//               'يجوز لنا الكشف عن المعلومات الشخصية لأي شخص يقوم بتقديم خدمات التدقيق أو الخدمات القانونية أو التشغيلية أو غيرها من الخدمات لنا. سوف نستخدم المعلومات التي لا تحدد هوية الفرد لهذه الأنشطة كلما كان ذلك ممكنًا بشكل معقول. بموجب قانون CCPA، من بين حقوق أخرى، يحق للمستهلكين في كاليفورنيا أن يطلبوا من الشركة التي تجمع البيانات الشخصية الكشف عن فئات وأجزاء محددة من البيانات الشخصية التي جمعتها الشركة عن المستهلكين، ومطالبة الشركة بحذف أي بيانات شخصية، وعدم بيعها. البيانات الشخصية للمستهلكين. إذا قمت بتقديم طلب، لدينا شهر واحد للرد عليك. إذا كنت ترغب في ممارسة أي من هذه الحقوق، فيرجى الاتصال بنا عبر دعم العملاء بموجب حقوق حماية البيانات الخاصة باللائحة العامة لحماية البيانات (GDPR)، يحق لكل مستخدم طلب نسخ من بياناتك الشخصية. قد نفرض عليك رسومًا صغيرة مقابل الخدمة، والحق في طلب تصحيح أي معلومات تعتقد أنها غير دقيقة، والحق في طلب مسح بياناتك الشخصية، وتقييد معالجتها، والاعتراض على معالجتنا لبياناتك الشخصية، ونقل البيانات التي لقد قمنا بجمع البيانات إلى منظمة أخرى أو إليك مباشرة في ظل ظروف معينة. إذا قمت بتقديم طلب، لدينا شهر واحد للرد عليك. إذا كنت ترغب في ممارسة أي من هذه الحقوق، يرجى الاتصال بنا عبر دعم العملاء',
//           'consent':
//               'باستخدام موقعنا وخدماتنا ومنتجاتنا، فإنك توافق بموجبه على سياسة الخصوصية الخاصة بنا وتوافق على شروطها. إذا كنت طبيبًا أو متخصصًا طبيًا تقوم بالتسجيل في هذا التطبيق، فمن خلال التسجيل في هذه الخدمة أو استخدامها، فإنك تؤكد بموجب هذا أن الاستخدام يقع على مسؤوليتك الخاصة، كما أنك تحرر وتوافق على إعفاء مقدمي الخدمة والمطورين والناشرين من المسؤولية عن العواقب الضارة. ، بما في ذلك على سبيل المثال لا الحصر المطالبات أو الإجراءات أو الإجراءات القانونية من قبل أطراف ثالثة أو فقدان أو خرق أي بيانات خاصة و/أو الأضرار التي لحقت نتيجة لذلك',
//           'consentTitle': 'موافقة',
//           'usageTitle': 'الاستخدام',
//           'disclosureTitle': 'إفشاء',
//           'informationWeCollect': 'المعلومات التي نجمعها',
//           'iHaveRead': 'لقد قرأت وفهمت',
//           'theTermsAndCondition': 'الشروط والأحكام',
//           'accept': 'يقبل',
//           'decline': 'انخفاض',
//           'height': 'ارتفاع',
//           'weight': 'وزن',
//           'add': 'يضيف',
//           'servicesHome': 'الخدمات (المنزلية)',
//           'teleConsultation': 'الاستشارة عن بعد',
//           'diagnostics': 'التشخيص',
//           'physio': 'فيزيائي',
//           'nursing': 'التمريض',
//           'caregiver': 'الراعي',
//           'respiratoryTherapy': 'العلاج التنفسي',
//           'dietitian': 'اخصائي تغذيه',
//           'serviceSelected': 'الخدمة مختارة',
//           'agree': 'يوافق',
//           'appointmentNotes': 'ملاحظات التعيين',
//           'deny': 'ينكر',
//           'search': 'يبحث',
//           'homeVisit': 'زيارة منزلية',
//           'online': 'متصل',
//           'subTotal': 'المجموع الفرعي',
//           'minFee': 'الحد الأدنى للرسوم',
//           'doctorSchedule': 'جدول الطبيب',
//           'fee': 'مصاريف',
//           'charges': 'رسوم',
//           'selectAddress': 'حدد العنوان',
//           'selectLocation': 'اختر موقعا',
//           'goodMorning': 'صباح الخير',
//           'token': 'رمز مميز',
//           'ecg': 'تخطيط القلب الكهربي',
//           'selectLanguage': 'اختار اللغة',
//           'hour': 'ساعة',
//           'homeService': 'خدمة الرعاية المنزلية',
//           'labInvestigationBooking': 'حجز الفحوصات المخبرية',
//           'experience': 'خبرة',
//           'paying': 'الدفع',
//           'serviceBooked': 'تم حجز الخدمة بنجاح',
//           'appointmentSuccessful': "تم حجز الموعد بنجاح. سوف تتلقى إخطارا",
//           'failedAppointment':
//               'Appointment failed please check your internet connection then try again.',
//           'favorites': 'المفضلة',
//           'noFavorites': 'لم تتم إضافة أي الأطباء المفضلين',
//           'contact': 'رقم الاتصال',
//           'province/state': 'المقاطعة/الولاية',
//           'editProfile': 'تعديل الملف الشخصي',
//           'mobNumber': 'رقم الهاتف المحمول',
//           'update': 'تحديث',
//           'healthanalysis': 'تحليل الصحة',
//           'herearesomehealth': 'فيما يلي بعض الحقائق الصحية حول',
//           'men': 'رجال',
//           'In': 'في',
//           'dubai': 'دبي الامارات العربية المتحدة',
//           'doctorName': 'اسم الطبيب',
//           'careGiver': 'الراعي',
//           'condition': 'حالة',
//           'disclaimer': 'تنصل',
//           'services': 'خدمات',
//           "manageYourHealth": 'إدارة صحتك معنا',
//           'go': 'يذهب',
//           'imaging': 'حجز التصوير',
//           'caretocure': 'من الرعاية إلى العلاج',
//           'specialities': 'التخصصات',
//           'consultatclinic': 'استشارة في العيادة',
//           'forgotpassword': 'كلمة سر منسية',
//           'ithappens':
//               'إذا حدث ذلك، يرجى إدخال البريد الإلكتروني المرتبط بحسابك',
//           'createpassword': 'إنشاء كلمة مرور جديدة',
//           'kindlyenter': 'يرجى إدخال كلمة مرور فريدة',
//           'oldpaasword': 'كلمة المرور القديمة',
//           'confirmpassword': 'تأكيد كلمة المرور',
         
//           'imagingbooking': 'حجز التصوير',
//           'imagingTitle': 'التصوير',
//           'completed': 'مكتمل',
//           'upcoming': 'القادمة',
//           'cancelled': 'ألغيت',
//           'noDataFound': 'لاتوجد بيانات!',
//           'service': 'خدمة',
//           'homeServices': 'خدمات منزلية',
//           'changePassword': 'تغيير كلمة المرور',
//           'modeOfPayment': 'طريقة الدفع'
