import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "welcometo": "Welcome To",
          "takecareof": "Take Care Of",
          "yourhealth": "Your Health!",
          "manageYourHealth": 'Manage your health with us',
          "with": "With",
          'goodmorning': "GOOD MORNING",
          'goodEvening': 'GOOD EVENING',
          'goodNight': 'GOOD NIGHT',
          'goodAfterNoon': 'GOOD AFTERNOON',
          'onlineOffline': 'Online & Offline ',
          'consultations': 'Consultations',
          'booknow': 'Book Now',
          'selectservices': 'Select Services',
          'homeSample': 'Home Sample',
          'imageBooking': 'Image Booking',
          'imagingbooking': 'Imaging Booking',
          'doctorConsultation': 'Doctor Consultation',
          'reports': 'Reports',
          'healthSummary': 'Health Summary',
          'healthAnalysis': 'Health Analysis',
          'todayAvailable': 'Today Available',
          'generalConsultation': 'General Consultation',
          'getAppointment': 'Get Appointment',
          'consultatclinic': 'Consult at Clinic',
          'home': 'Home',
          'profile': 'Profile',
          'schedule': 'Schedule',
          'help': 'Help',
          'helpful': "Helpful!",
          'helpfull': "Helpful",
          'history': 'History',
          'familyMembers': 'Family Members',
          'location': 'Location',
          'wallet': 'Wallet',
          'packages': 'Packages',
          'forgotPassword': 'Forgot Password',
          'biometric': 'Biometric',
          'privacyPolicy': 'Privacy Policy',
          'termsAndConditions': 'Terms & Conditions',
          'logout': 'Logout',
          'labInvestions': 'Lab Investigations',
          'selectTest': 'Select Test',
          'description': 'Description',
          'address': 'Address',
          'paymentMethod': 'Payment Gateway',
          'prescribedBy': 'Prescribed By',
          'self': 'Self',
          'doctor': 'Doctor',
          'outdoorDoctor': 'Outdoor Doctor',
          'select Doctor': 'Select Doctor',
          'summary': 'Summary',
          'datehour': 'Date & Hour',
          'package': 'Package',
          'test': 'Test',
          'price': 'Price',
          'grandTotal': 'Grand Total',
          'appointmentConfirm': 'Book Appointment',
          'attachPrescription': 'Attach Prescription',
          'login': 'LOGIN',
          'Login': 'Login',
          'donthaveanAccount': 'Don\'t have an Account',
          'register': 'Register',
          'registerNow': 'Register Now',
          'fullName': 'Full Name',
          'yourMobNumber': 'Your Mobile Number',
          'email': 'Email',
          'dateOfBirth': 'Date of Birth',
          'gender': 'Gender',
          'password': 'Password',
          'retypePassword': ' Re-type Password',
          'country': 'Country',
          'state': 'State',
          'city': 'City',
          'street': 'Street',
          'alreadyHaveAnAccount': 'Already have an account?',
          'signin': 'Sign in',
          'registered': 'Registered',
          'registrationCompleted':
              'Registration has been Successfully Completed',
          'ok': 'OK',
          'payfromYourWallet': 'Pay from your Wallet',
          'payOnline': 'Pay Online',
          'payAtClinic': 'Pay At Clinic',
          'congratulations': 'Congratulations',
          'myAppointments': 'My Appointments',
          'bookyourAppointments': 'Book your Appointment',
          'searchDoctor': 'Search Doctor',
          'patients': "Patients",
          'yearExperience': 'Years of Experience',
          'rating': 'Rating',
          'reviews': 'Reviews',
          'descriptions': 'Descriptions',
          'workingTime': 'Working Time',
          'online&Clinic': 'Online & Home Consultation Charges',
          'bookAppointment': 'Book Appointment',
          'welcomeTo': 'Welcome to',
          'username': 'Username',
          'oopsFailed': 'Oops, Failed',
          'appointmentFailed': 'Appointment Failed',
          'checkInternet':
              'Please Check your Internet Connection And Try again',
          'appointmentBooked': 'Appointment Booked Successfully',
          'viewAppointment': 'View Appointment',
          'cancel': 'Cancel',
          'glucose': "Glucose",
          'bloodPressure': 'Blood Pressure values',
          'measurements': 'Measurements',
          'connect': 'Connect',
          'pulse': 'Pulse',
          'temperature': 'Temperature',
          'labTestResult': 'Lab Test Result',
          'status': 'Status',
          'pending': 'Pending',
          'allergies': 'Allergies',
          'addGlucose': 'Add Glucose',
          'normal': 'Normal',
          'fasting': 'Fasting',
          'values': 'Values',
          'condition': 'Condition',
          'saveRecord': 'Save Record',
          'calculate': 'Calculate',
          'bmiCalculator': 'BMI Calculator',
          'BMI': 'BMI',
          'glucoseLevelMonitor': 'Glucose Level Monitor',
          'enterValue': 'Enter Value',
          'goodAfternoon': 'GOOD AFTERNOON',
          'collectLocationData':
              'Tabib AlBait Patient Care collects Location data to enable Home Sampling Services even when is closed or not in use',
          'permissions': 'Permissions',
          'deleteAccount': 'Delete Account',
          'languages': 'Language',
          'identityNumber': 'Identity Number',
          'signup': 'Sign up',
          'bpm': 'BPM',
          'date': 'Date',
          'time': 'Time',
          'searchForSpecialities': 'Search For Specialists',
          'specialities': 'Specialities',
          'consultNow': 'Consult Online',
          'specialists': 'Specialists',
          'upcomingAppointments': 'Upcoming Appointments',
          'dateAndTime': 'Date and Time',
          'reschedule': 'Reschedule',
          'onlineConsultation': 'Online Consultation',
          'information1':
              'Our system and apps are mainly targeting Health Care and medical. We are collecting some other information and permissions in our apps to improve user experience and app functionality. The information we collect is ephemerally processed i.e. it is only used to start some service or functionality involved inside the application and not used after it is stopped. Some important one are mentioned below with prominent disclosure/reasons for collection',
          'information2':
              'Location: In order to show nearby doctors, app needs to get this permission from user. By enabling Location-Based services on your device, you agree and acknowledge  that (a) device data that is collected from you is directly relevant to your use of the App, (b) We may provide Location-Based services related to and based on your then-current location, and (c) We may use any information collected in connection with its provision of the App.For video calling between doctor and patient.For audio calling  between doctor and patient (a)User/Patient can upload profile picture (b) User/Patient can upload health records and files for doctor to examine (c)User/Patient can download and view reports etc.',
          'usage':
              'We use the informative we collect in various ways, including to: (a)Provide, operate, and maintain our services and products (b)Understand and analyze how you use our services and products (c)Develop new product, services features, and functionality (d) Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the website, and for marketing and promotional purposes (e) Send your emails (f) Find and prevent fraud.',
          'disclosure':
              'We may disclose personal information to any person performing audit, legal, operational or other services for us. We will use information which does not identify the individual for these activities whenever reasonably possible. Under the CCPA, among other rights, California consumers have the  right to Request that a business that collects personal data disclose the categories and specific pieces of personal data that a business has collected about consumers, Request that a business delete any personal data, not sell the consumers personal data. If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us via customer supportUnder the GDPR Data Protection Rights, every user is entitled to the right to request copies of your personal data. We may charge you a small fell for the service, right to request that we correct any information you believe in inaccurate, right to request that we erase your personal data, restrict its processing, object to our processing of your personal, transfer the data that we have collected to another organization or directly to you data under certain conditions. If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us via customer support',
          'consent':
              'By using our website, services & products, you hereby consent to our Privacy Policy and agree to its terms. If you are a doctor or medical professional registering on this App, by enrolling in or using this service, you hereby confirm that usage is at your own risk and you release and agree to hold harmless the providers, developers, deployers from liability for adverse consequences, including but limited to claims, actions or legal proceedings by third parties, loss or breach of any private data and/or damages suffered as a result thereof.',
          'consentTitle': 'Consent',
          'usageTitle': 'Usage',
          'disclosureTitle': 'Disclosure',
          'informationWeCollect': 'Information we Collect',
          'iHaveRead': 'I have read and understand',
          'theTermsAndCondition': ' the Terms and Conditions',
          'accept': 'Accept',
          'decline': 'Decline',
          'height': 'Height',
          'weight': 'Weight',
          'add': 'Add',
          'servicesHome': 'Services (Home)',
          'teleConsultation': 'Tele Consultation',
          'diagnostics': 'Diagnostics',
          'physio': 'Physio',
          'nursing': 'Nursing',
          'caregiver': 'Caregiver',
          'respiratoryTherapy': 'Respiratory Therapy',
          'dietitian': 'Dietitian',
          'serviceSelected': 'Service Selected',
          'collectesData':
              'collects Location data to enable  Services Home even when is closed or not in use',
          'agree': 'Agree',
          'appointmentNotes': 'Appointment Notes',
          'deny': 'Deny',
          'search': 'Search',
          'homeVisit': 'Home Visit',
          'online': 'Online',
          'subTotal': 'Sub Total',
          'minFee': 'Min. Fee',
          'doctorSchedule': 'Doctor Schedule',
          'fee': 'Fee',
          'charges': 'Charges',
          'selectAddress': 'Select Address',
          'selectLocation': 'Select Location',
          'goodMorning': 'GOOD MORNING',
          'token': 'Token',
          'ecg': 'ECG',
          'selectLanguage': 'Select Language',
          'english': 'English',
          'arabic': 'Arabic',
          'hour': 'Hour',
          'homeService': 'Home Care Service',
          'labInvestigationBooking': 'Lab Investigation Booking',
          'experience': 'Experience',
          'paying': 'Paying',
          'serviceBooked': 'Service Booked Successfully.',
          'appointmentSuccessful':
              "Appointment Successfully Booked. You Will receive a notification",
          'failedAppointment':
              'Appointment failed please check your internet connection then try again.',
          'favorites': 'Favorites',
          'noFavorites': 'No Favorite Doctors Added',
          'contact': 'Contact no.',
          'province/state': 'Province/State',
          'editProfile': 'Edit Profile',
          'update': 'Update',
          'healthanalysis': 'Health Analysis',
          'herearesomehealth': 'Here are some Health facts about ',
          'men': 'Men',
          'In': 'in',
          'dubai': 'Dubai, UAE ',
          'doctorName': 'Doctor Name',
          'careGivers': 'Caregiver',
          'disclaimer': 'Disclaimer',
          'services': 'Services',
          'go': 'Go',
          'imaging': 'Imaging Booking',
          'caretocure': 'FROM CARE TO CURE',
          'forgotpassword': 'Forgotten Password',
          'ithappens':
              'It happen, kindly enter the email associated with your account',
          'createpassword': 'Create New Password',
          'kindlyenter': 'Kindly enter a unique password',
          'oldpaasword': 'Old Password',
          'confirmpassword': 'Confirm Password',
          'changepassword': 'Change Password',
          'imagingTitle': 'Imaging',
          'completed': 'Completed',
          'upcoming': 'Upcoming',
          'cancelled': 'Cancelled',
          'noDataFound': 'No data Found!',
          'service': 'Service',
          'homeServices': 'Home Services',
          'changePassword': 'Change Password',
          'modeOfPayment': 'Mode Of Payment'
        },
        "ar_SA": {
          "welcometo": "مرحبا بك في",
          "takecareof": "اعتني ب ",
          "yourhealth": "صحتك!",
          "with": "مع",
          'goodmorning': "صباح الخير",
          'goodEvening': 'مساء الخير',
          'goodNight': 'طاب مساؤك',
          'goodAfterNoon': 'مساء الخير',
          'onlineOffline': 'متصل غير متصل',
          'consultations': 'استشارات',
          'booknow': 'احجز الآن',
          'selectservices': 'حدد الخدمات',
          'homeSample': 'عينة المنزل',
          'imageBooking': 'حجز الصور',
          'doctorConsultation': 'استشارة الطبيب',
          'reports': 'التقارير',
          'healthSummary': 'ملخص الصحة',
          'healthAnalysis': 'التحليل الصحي',
          'todayAvailable': 'متوفر اليوم',
          'generalConsultation': 'الاستشارة العامة',
          'getAppointment': 'احصل على موعد',
          'home': 'بيت',
          'profile': 'حساب تعريفي',
          'schedule': 'جدول',
          'help': 'يساعد',
          'history': 'تاريخ',
          'familyMembers': 'أفراد الأسرة',
          'location': 'موقع',
          'wallet': 'محفظة',
          'packages': 'الحزم',
          'forgotPassword': 'هل نسيت كلمة السر',
          'biometric': 'بصمات',
          'privacyPolicy': 'سياسة الخصوصية',
          'termsAndConditions': 'البنود و الظروف',
          'logout': 'تسجيل خروج',
          'labInvestions': 'التحقيقات المخبرية',
          'selectTest': 'حدد اختبار',
          'description': 'وصف',
          'address': 'عنوان',
          'paymentMethod': 'طريقة الدفع او السداد',
          'prescribedBy': 'المنصوص عليها',
          'self': 'الذات',
          'doctor': 'طبيب',
          'outdoorDoctor': 'طبيب خارجي',
          'select Doctor': 'اختر الطبيب',
          'summary': 'ملخص',
          'datehour': 'التاريخ والساعة',
          'package': 'طَرد',
          'test': 'امتحان',
          'price': 'سعر',
          'grandTotal': 'المجموع الإجمالي',
          'appointmentConfirm': 'موعد الكتاب',
          'attachPrescription': 'إرفاق وصفة طبية',
          'login': 'تسجيل الدخول',
          'Login': 'تسجيل الدخول',
          'donthaveanAccount': 'لا تملك حساب',
          'register': 'يسجل',
          'registerNow': 'سجل الان',
          'fullName': 'الاسم الكامل',
          'yourMobNumber': 'رقم هاتفك',
          'email': 'بريد إلكتروني',
          'dateOfBirth': 'تاريخ الميلاد',
          'gender': 'جنس',
          'password': 'كلمة المرور',
          'retypePassword': 'أعد إدخال كلمة السر',
          'country': 'دولة',
          'state': 'ولاية',
          'city': 'مدينة',
          'street': 'شارع',
          'alreadyHaveAnAccount': 'هل لديك حساب؟',
          'signin': 'تسجيل الدخول',
          'registered': 'مسجل',
          'registrationCompleted': 'تم التسجيل بنجاح',
          'ok': 'نعم',
          'payfromYourWallet': 'ادفع من محفظتك',
          'payOnline': 'ادفع عبر الإنترنت',
          'payAtClinic': 'الدفع في العيادة',
          'congratulations': 'تهانينا',
          'myAppointments': 'مواعيدي',
          'bookyourAppointments': 'احجز موعدك',
          'searchDoctor': 'البحث عن الأطباء',
          'patients': "مرضى",
          'yearExperience': 'سنوات من الخبرة',
          'rating': 'التقييمات',
          'reviews': 'التعليقات',
          'descriptions': 'الأوصاف',
          'workingTime': 'وقت العمل',
          'online&Clinic': 'رسوم الاستشارة عبر الإنترنت والعيادة',
          'bookAppointment': 'موعد الكتاب',
          'welcomeTo': 'مرحبا بك في',
          'username': 'اسم المستخدم',
          'oopsFailed': 'عفوًا، فشل',
          'appointmentFailed': 'فشل الموعد',
          'checkInternet': 'الرجاء التحقق من اتصالك بالإنترنت وحاول مرة أخرى',
          'appointmentBooked': 'تم حجز الموعد بنجاح',
          'viewAppointment': 'عرض الموعد',
          'cancel': 'يلغي',
          'glucose': "الجلوكوز",
          'bloodPressure': 'ضغط الدم',
          'measurements': 'قياسات',
          'connect': 'يتصل',
          'pulse': 'نبض',
          'temperature': 'درجة حرارة',
          'labTestResult': 'نتيجة الاختبار المعملي',
          'status': 'حالة',
          'pending': 'قيد الانتظار',
          'allergies': 'الحساسية',
          'addGlucose': 'أضف الجلوكوز',
          'normal': 'طبيعي',
          'fasting': 'صيام',
          'values': 'قيم',
          'condtition': 'حالة',
          'saveRecord': 'حفظ السجل',
          'calculate': 'احسب',
          'bmiCalculator': 'حاسبة مؤشر كتلة الجسم',
          'BMI': 'مؤشر كتلة الجسم',
          'glucoseLevelMonitor': 'مراقب مستوى الجلوكوز',
          'enterValue': 'أدخل القيمة',
          'collectLocationData':
              'يقوم طبيب البيت لرعاية المرضى بجمع بيانات الموقع لتمكين خدمات أخذ العينات المنزلية حتى عندما تكون مغلقة أو غير مستخدمة',
          'permissions': 'الأذونات',
          'deleteAccount': 'حذف الحساب',
          'languages': "لغة",
          'identityNumber': 'رقم الهوية',
          'signup': 'اشتراك',
          'bpm': 'نبضة في الدقيقة',
          'date': 'تاريخ',
          'time': 'وقت',
          'searchForSpecialities': 'البحث عن القسم',
          'consultNow': 'استشر عبر الإنترنت',
          'specialists': 'المتخصصين',
          'upcomingAppointments': 'المواعيد القادمة',
          'dateAndTime': 'التاريخ و الوقت',
          'reschedule': 'إعادة جدولة',
          'onlineConsultation': 'التشاور عبر الإنترنت',
          'information1':
              'يستهدف نظامنا وتطبيقاتنا بشكل أساسي الرعاية الصحية والطبية. نقوم بجمع بعض المعلومات والأذونات الأخرى في تطبيقاتنا لتحسين تجربة المستخدم ووظائف التطبيق. تتم معالجة المعلومات التي نجمعها بشكل مؤقت، أي أنها تستخدم فقط لبدء بعض الخدمات أو الوظائف الموجودة داخل التطبيق ولا يتم استخدامها بعد إيقافها. تم ذكر بعض الأمور المهمة أدناه مع الإفصاح/أسباب التجميع البارزة',
          'information2':
              'الموقع: لإظهار الأطباء القريبين، يحتاج التطبيق إلى الحصول على هذا الإذن من المستخدم. من خلال تمكين الخدمات المستندة إلى الموقع على جهازك، فإنك توافق وتقر بأن (أ) بيانات الجهاز التي يتم جمعها منك ذات صلة مباشرة باستخدامك للتطبيق، (ب) قد نقدم خدمات تعتمد على الموقع تتعلق وتستند إلى موقعك الحالي في ذلك الوقت، و (ج) يجوز لنا استخدام أي معلومات تم جمعها فيما يتعلق بتوفير التطبيق. لإجراء مكالمات فيديو بين الطبيب والمريض. لإجراء مكالمات صوتية بين الطبيب والمريض (أ) يمكن للمستخدم/المريض تحميل صورة الملف الشخصي (ب) يمكن للمستخدم/المريض تحميل السجلات والملفات الصحية ليقوم الطبيب بفحصها (ج) يمكن للمستخدم/المريض تنزيل وعرض التقارير وما إلى ذلك.',
          'usage':
              'نحن نستخدم المعلومات التي نجمعها بطرق مختلفة، بما في ذلك: (أ) توفير خدماتنا ومنتجاتنا وتشغيلها وصيانتها (ب) فهم وتحليل كيفية استخدامك لخدماتنا ومنتجاتنا (ج) تطوير منتج جديد وميزات الخدمات و الوظيفة (د) التواصل معك، إما بشكل مباشر أو من خلال أحد شركائنا، بما في ذلك خدمة العملاء، لتزويدك بالتحديثات والمعلومات الأخرى المتعلقة بالموقع، ولأغراض تسويقية وترويجية (هـ) إرسال رسائل البريد الإلكتروني الخاصة بك (و) البحث عن الاحتيال ومنعه',
          'disclosure':
              'يجوز لنا الكشف عن المعلومات الشخصية لأي شخص يقوم بتقديم خدمات التدقيق أو الخدمات القانونية أو التشغيلية أو غيرها من الخدمات لنا. سوف نستخدم المعلومات التي لا تحدد هوية الفرد لهذه الأنشطة كلما كان ذلك ممكنًا بشكل معقول. بموجب قانون CCPA، من بين حقوق أخرى، يحق للمستهلكين في كاليفورنيا أن يطلبوا من الشركة التي تجمع البيانات الشخصية الكشف عن فئات وأجزاء محددة من البيانات الشخصية التي جمعتها الشركة عن المستهلكين، ومطالبة الشركة بحذف أي بيانات شخصية، وعدم بيعها. البيانات الشخصية للمستهلكين. إذا قمت بتقديم طلب، لدينا شهر واحد للرد عليك. إذا كنت ترغب في ممارسة أي من هذه الحقوق، فيرجى الاتصال بنا عبر دعم العملاء بموجب حقوق حماية البيانات الخاصة باللائحة العامة لحماية البيانات (GDPR)، يحق لكل مستخدم طلب نسخ من بياناتك الشخصية. قد نفرض عليك رسومًا صغيرة مقابل الخدمة، والحق في طلب تصحيح أي معلومات تعتقد أنها غير دقيقة، والحق في طلب مسح بياناتك الشخصية، وتقييد معالجتها، والاعتراض على معالجتنا لبياناتك الشخصية، ونقل البيانات التي لقد قمنا بجمع البيانات إلى منظمة أخرى أو إليك مباشرة في ظل ظروف معينة. إذا قمت بتقديم طلب، لدينا شهر واحد للرد عليك. إذا كنت ترغب في ممارسة أي من هذه الحقوق، يرجى الاتصال بنا عبر دعم العملاء',
          'consent':
              'باستخدام موقعنا وخدماتنا ومنتجاتنا، فإنك توافق بموجبه على سياسة الخصوصية الخاصة بنا وتوافق على شروطها. إذا كنت طبيبًا أو متخصصًا طبيًا تقوم بالتسجيل في هذا التطبيق، فمن خلال التسجيل في هذه الخدمة أو استخدامها، فإنك تؤكد بموجب هذا أن الاستخدام يقع على مسؤوليتك الخاصة، كما أنك تحرر وتوافق على إعفاء مقدمي الخدمة والمطورين والناشرين من المسؤولية عن العواقب الضارة. ، بما في ذلك على سبيل المثال لا الحصر المطالبات أو الإجراءات أو الإجراءات القانونية من قبل أطراف ثالثة أو فقدان أو خرق أي بيانات خاصة و/أو الأضرار التي لحقت نتيجة لذلك',
          'consentTitle': 'موافقة',
          'usageTitle': 'الاستخدام',
          'disclosureTitle': 'إفشاء',
          'informationWeCollect': 'المعلومات التي نجمعها',
          'iHaveRead': 'لقد قرأت وفهمت',
          'theTermsAndCondition': 'الشروط والأحكام',
          'accept': 'يقبل',
          'decline': 'انخفاض',
          'height': 'ارتفاع',
          'weight': 'وزن',
          'add': 'يضيف',
          'servicesHome': 'الخدمات (المنزلية)',
          'teleConsultation': 'الاستشارة عن بعد',
          'diagnostics': 'التشخيص',
          'physio': 'فيزيائي',
          'nursing': 'التمريض',
          'caregiver': 'الراعي',
          'respiratoryTherapy': 'العلاج التنفسي',
          'dietitian': 'اخصائي تغذيه',
          'serviceSelected': 'الخدمة مختارة',
          'agree': 'يوافق',
          'appointmentNotes': 'ملاحظات التعيين',
          'deny': 'ينكر',
          'search': 'يبحث',
          'homeVisit': 'زيارة منزلية',
          'online': 'متصل',
          'subTotal': 'المجموع الفرعي',
          'minFee': 'الحد الأدنى للرسوم',
          'doctorSchedule': 'جدول الطبيب',
          'fee': 'مصاريف',
          'charges': 'رسوم',
          'selectAddress': 'حدد العنوان',
          'selectLocation': 'اختر موقعا',
          'goodMorning': 'صباح الخير',
          'token': 'رمز مميز',
          'ecg': 'تخطيط القلب الكهربي',
          'selectLanguage': 'اختار اللغة',
          'hour': 'ساعة',
          'homeService': 'خدمة الرعاية المنزلية',
          'labInvestigationBooking': 'حجز الفحوصات المخبرية',
          'experience': 'خبرة',
          'paying': 'الدفع',
          'serviceBooked': 'تم حجز الخدمة بنجاح',
          'appointmentSuccessful': "تم حجز الموعد بنجاح. سوف تتلقى إخطارا",
          'failedAppointment':
              'Appointment failed please check your internet connection then try again.',
          'favorites': 'المفضلة',
          'noFavorites': 'لم تتم إضافة أي الأطباء المفضلين',
          'contact': 'رقم الاتصال',
          'province/state': 'المقاطعة/الولاية',
          'editProfile': 'تعديل الملف الشخصي',
          'mobNumber': 'رقم الهاتف المحمول',
          'update': 'تحديث',
          'healthanalysis': 'تحليل الصحة',
          'herearesomehealth': 'فيما يلي بعض الحقائق الصحية حول',
          'men': 'رجال',
          'In': 'في',
          'dubai': 'دبي الامارات العربية المتحدة',
          'doctorName': 'اسم الطبيب',
          'careGiver': 'الراعي',
          'condition': 'حالة',
          'disclaimer': 'تنصل',
          'services': 'خدمات',
          "manageYourHealth": 'إدارة صحتك معنا',
          'go': 'يذهب',
          'imaging': 'حجز التصوير',
          'caretocure': 'من الرعاية إلى العلاج',
          'specialities': 'التخصصات',
          'consultatclinic': 'استشارة في العيادة',
          'forgotpassword': 'كلمة سر منسية',
          'ithappens':
              'إذا حدث ذلك، يرجى إدخال البريد الإلكتروني المرتبط بحسابك',
          'createpassword': 'إنشاء كلمة مرور جديدة',
          'kindlyenter': 'يرجى إدخال كلمة مرور فريدة',
          'oldpaasword': 'كلمة المرور القديمة',
          'confirmpassword': 'تأكيد كلمة المرور',
          'changepassword': 'تغيير كلمة المرور',
          'imagingbooking': 'حجز التصوير',
          'imagingTitle': 'التصوير',
          'completed': 'مكتمل',
          'upcoming': 'القادمة',
          'cancelled': 'ألغيت',
          'noDataFound': 'لاتوجد بيانات!',
          'service': 'خدمة',
          'homeServices': 'خدمات منزلية',
          'changePassword': 'تغيير كلمة المرور',
          'modeOfPayment': 'طريقة الدفع'
        }
      };
}
