import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          //drawer
          'changepassword': 'Change Password',
          'biometric': 'Biometric',
          'languages': 'Languages',
          'privacyPolicy': 'Privacy Policy',
          'termsAndConditions': 'Terms & Conditions',
          'deleteAccount': 'Delete Account',
          'logout': 'Logout',
          //Dashboard
          'goodmorning': "G o o d  M o r n i n g",
          'goodEvening': 'G o o d  E v e n i n g',
          'goodNight': 'G o o d  N i g h t',
          'goodAfterNoon': 'G o o d  A f t e r n o o n',
          'hi': 'Hi,',
          'todayappointments': 'Today \nAppointments',
          'appointmenthistory': 'Appointment \nHistory',
          'registrationordering': 'Registration \n& Ordering',
          'comingsoon': 'Coming \nSoon',
          'registration': 'Registration',
          'registerpatient': 'Registered Patient',
          //profile
          'profile': 'Profile',
          'vehiclenumber': 'Vehicle Number',
          'govid': 'Government ID',
          'contact': 'Contact No',
          'dob': 'Date of Birth',
          'address': 'Address',
          //changepassword
          'welcometo': 'Welcome To',
          'helpful': 'Helpful.',
          'oldpassword': 'Enter Old Password',
          'newpassword': 'Enter New Password',
          'confirmpassword': 'Confirm New Password',
          'submit': 'Submit',
          'pleaseoldpassword': "Please enter old password",
          'pleasenewpassword': 'Please enter new password',
          'pleaseconfirmpassword': 'Please confirm new password',
          'passwordnotmatch': 'Passwords do not match',
          'passwordsuccess': 'Password changed successfully',
          'passwordfailed': 'Old Password is wrong',
          //notification
          'notification': 'Notification',
          //appointments
          'todayappointment': 'Today Appointments',
          'appointmenhistory': 'Appointment History',
          'from': 'From',
          'to': 'To',
          'test': 'Test  |',
          'addres': 'Address  |',
          'viewinformation':'View Information',
          'startride':'Start Ride',
          'ridestatus':'Ride Status',
          'wanttostart':'Do you want to start Ride?',
          'ridestarted':'Ride Started Succefully!',
          'yes':'Yes',
          'no':'No',
          'cancel':'Cancel',
          'arrived':'Arrived',
          'cancelride':'Cancel Ride',
          'remarks':'Remarks',
          'enterremarks':'Enter Remarks',
          'pleaseenterremarks':"Please Enter Remarks First",
          'pleaseselect':"Please Select Lab",
          'ok':'OK',
          'arrivedatlocation':'Are You Arrived at Patient Location?',
          'checkin':'Check In',
          'paymentmethod':'   Payment Method',
          'discount':'Discount:',
          'paymentstatus':'Payment Status:',
          'totalamount':'Total Amount:',
          'percentage':"Percentage",
          'amount':'Amount',
          'samplecollected':'Sample Collected',
          'inroutelab':'In Route to Lab',
          'selectlab':'Select Lab',
          'deliversample':'Deliver Sample',
          'ridecompleted':'Ride Completed',
          'thankyou':'Thank You',
          'backhome':'BACK HOME',
          'order':'Order:',

          //Registration
          'registernow':'Register Now',
          'fullname': 'Full Name',
          'email': 'Email',
          'gender': 'Gender',
          'country': 'Country',
          'state': 'State',
          'city': 'City',
          'relation': 'Relation',
          'nationalid': 'National ID 123-4567-8910111-2',
          'entername': 'Enter your full name',
          'entervalidno': 'Please enter a valid number',
          'enteremail': 'Enter Your Email',
          'selectgender': 'Please select a gender',
          'enterid': 'Enter ID Number',
          'enteraddress': 'Enter Your Address',
          'vehicletype':'Vehicle Type',
          'vehicleno':'Vehicle Number',
          'liscenceno':'Liscence Number',
          'password':'Password',
          'repassword':'Re-Password',
          'entervehicle':'Enter Vehicle Number',
          'enterliscenceno':'Enter Liscence Number',
          'passnotmatch':'Passwords do not match!',
          'entervaliddata':'Please Enter Valid Data',
          'register':'Register',
          'alreadyhaveacount':'Already have an account?',
          'signin':'Sign In',
          //Login
          'login':'LOGIN',
          'username':'Username',
          'enterusername':'Please Enter Your Username' ,
          'invalid':'Invalid Username and Password', 
          'dontaccount':'Don`t Have An Account?',  
          //labinvestigation
          'labinvestigation':'Lab Investigation',
          'selecttest':'Select Test',
          'pleaseselectpaymentmethod':'Please Select Payment Method',

          //terms&condition
          'disclaimer': 'Disclaimer',
          'consentTitle': 'Consent',
            'consent':'By using our website, services and products, you hereby consent to our Privacy Policy and agree to its terms. If you are a doctor or medical professional registering for this Application, by registering for or using this Service, you hereby confirm that use is at your own risk, and you release and agree to release the Service Providers, Developers and Publishers from liability for adverse consequences. , including but not limited to claims, actions or legal proceedings by third parties or loss or breach of any private data and/or damages suffered as a result thereof',
          'informationWeCollect': 'Information we collect',
           'information1':'Our system and applications mainly target healthcare and medical care. We collect certain other information and permissions in our apps to improve user experience and app functionality. The information we collect is processed temporarily, that is, it is only used to start certain services or functions within the application and is not used after they have been stopped. Some important matters are mentioned below along with salient disclosure/reasons for aggregation',
          'information2':'Location: To show nearby doctors, the app needs to get this permission from the user. By enabling location-based services on your device, you agree and acknowledge that (a) the device data collected from you is directly relevant to your use of the application, (b) we may provide location-based services that relate to and are based on your then-current location, and (c) ) We may use any information collected in connection with providing the Application. To make video calls between doctor and patient. To make voice calls between doctor and patient (a) User/patient can upload profile picture (b) User/patient can upload health records and files for doctor to check (c) User/patient can download and view reports etc.',
         'usageTitle': 'The Use',
          'usage':'We use the information we collect in various ways, including: (a) providing, operating, and maintaining our Services and Products (b) understanding and analyzing how you use our Services and Products (c) developing new product and Services features and functionality (d) communicating with you, either directly or Through one of our partners, including for customer service, to provide you with updates and other information relating to the site, and for marketing and promotional purposes (e) send you emails (f) detect and prevent fraud', 
          'disclosureTitle': 'Disclosure',
           'disclosure':'We may disclose personal information to anyone who provides audit, legal, operational or other services to us. We will use information that does not identify an individual for these activities whenever reasonably possible. Under the CCPA, Among other rights, California consumers have the right to request that a business that collects personal data disclose the categories and specific pieces of personal data that a business has collected about consumers, to request that the business delete any personal data, and not to sell it. Personal data of consumers. If you submit a request, we have one month to respond to you. If you wish to exercise any of these rights, please contact us via Customer Support Under your data protection rights under the General Data Protection Regulation (GDPR), Every user has the right to request copies of your personal data. We may charge you a small fee for the Service, the right to request that we correct any information that you believe is inaccurate, the right to request that we erase your personal data, restrict its processing, object to our processing of your personal data, transfer the data we have collected to another organization or directly to you under certain circumstances. If you submit a request, we have one month to respond to you. If you wish to exercise any of these rights, please contact us via Customer Support',
          'iHaveRead': 'I have read and understood',
          'theTermsAndCondition': 'Terms and Conditions',
          'labqeue':'Lab Queue',
          'samplecollection':'Sample Collection',
          'call':'Call',
          'message':'Message'
          




          
        },
        "ar_SA": {
          //drawer
          'changepassword': 'تغيير كلمة المرور',
          'biometric': 'بصمات',
          'languages': 'اللغات',
          'privacyPolicy': 'سياسة الخصوصية',
          'termsAndConditions': 'البنود و الظروف',
          'deleteAccount': 'حذف الحساب',
          'logout': 'تسجيل خروج',
          //Dashboard
          'goodmorning': "صباح الخير",
          'goodEvening': 'مساء الخير',
          'goodNight': 'طاب مساؤك',
          'goodAfterNoon': 'مساء الخير',
          'hi': 'أهلاً,',
          'todayappointments': 'مواعيد اليوم',
          'appointmenthistory': 'تاريخ التعيين',
          'registrationordering': 'التسجيل والطلب',
          'comingsoon': 'قريباً',
          'registration': 'تسجيل',
          'registerpatient': 'مريض مسجل',
          //profile
          'vehiclenumber': 'عدد المركبات',
          'govid': 'معرف الحكومة',
          'contact': 'رقم الاتصال',
          'dob': 'تاريخ الميلاد',
          'address': 'عنوان',
          'profile': 'حساب تعريفي',
          //changepassword
          'welcometo': 'مرحبا بك في',
          'helpful': 'Helpful.',
          'oldpassword': 'أدخل كلمة المرور القديمة',
          'newpassword': 'أدخل كلمة المرور الجديدة',
          'confirmpassword': 'تأكيد كلمة المرور الجديدة',
          'submit': 'يُقدِّم',
          'pleaseoldpassword': "الرجاء إدخال كلمة المرور القديمة",
          'pleasenewpassword': 'الرجاء إدخال كلمة المرور الجديدة',
          'pleaseconfirmpassword': 'كلمة المرور غير متطابقة',
          'passwordnotmatch': 'كلمة المرور غير متطابقة',
          'passwordsuccess': 'تم تغيير كلمة المرور بنجاح',
          'passwordfailed': 'كلمة المرور القديمة خاطئة',
          //Notification
          'notification': 'إشعار',
          //appointments
          'todayappointment': 'مواعيد اليوم',
          'appointmenhistory': 'تاريخ التعيين',
          'from': 'من',
          'to': 'إلى',
          'test': 'امتحان   | ',
          'addres': 'عنوان   | ',
           'viewinformation':'عرض المعلومات',
           'startride':'ابدأ الركوب',
            'ridestatus':'حالة الركوب',
          'wanttostart':'هل تريد أن تبدأ الركوب',
          'yes':'نعم',
          'no':'لا',
          'cancel':'يلغي',
          'arrived':'وصل',
          'cancelride':'إلغاء الرحلة',
          'remarks':'ملاحظات',
          'enterremarks':'أدخل الملاحظات',
          'ok':'تمام',
          'arrivedatlocation':'هل وصلت إلى موقع المريض',
          'checkin':'تحقق في',
          'paymentmethod':'طريقة الدفع او السداد',
          'discount':'تخفيض:',
          'paymentstatus':'حالة السداد:',
          'totalamount':'المبلغ الإجمالي:',
          'percentage':'نسبة مئوية',
          'amount':'كمية',
          'samplecollected':'العينة التي تم جمعها',
          'inroutelab':'في الطريق إلى المختبر',
          'selectlab':'حدد المختبر',
          'deliversample':'تسليم العينة',
          'ridecompleted':'اكتملت الرحلة',
          'thankyou':'شكرًا لك',
          'backhome':'العودة إلى المنزل',
          'order':'طلب:',
          'ridestarted':'بدأت الرحلة بنجاح!',
          'pleaseselect':"الرجاء اختيار المختبر",
           'labqeue':'قائمة انتظار المختب',
          

          //Registration
          'registernow':'سجل الان',
          'fullname': 'الاسم الكامل',
          'email': 'البريد الإلكتروني',
          'gender': 'الجنس',
          'country': 'البلد',
          'state': 'الولاية',
          'city': 'المدينة',
          'relation': 'علاقة',
          'nationalid': 'الهوية الوطنية 123-4567-8910111-2',
          'entername': 'أدخل اسمك الكامل',
          'entervalidno': 'من فضلك أدخل رقما صالحا',
          'enteremail': 'أدخل بريدك الإلكتروني',
          'selectgender': 'الرجاء تحديد الجنس',
          'enterid': 'أدخل رقم الهوية',
          'enteraddress': 'أدخل عنوانك',
          'vehicletype':'نوع السيارة',
          'vehicleno':'عدد المركبات',
          'liscenceno':'رقم الرخصة',
          'password':'كلمة المرور',
          'repassword':'إعادة كلمة المرور',
          'entervehicle':'أدخل رقم السيارة',
          'enterliscenceno':'أدخل رقم الترخيص',
          'passnotmatch':'كلمة السر غير مطابقة!',
          'register':'يسجل',
          'alreadyhaveacount':'لديك حساب بالفعل؟',
          'signin':'تسجيل الدخول',
          'entervaliddata':'الرجاء إدخال بيانات صحيحة',
          //Login
          'login':'تسجيل الدخول',
          'username':'اسم المستخدم',
          'enterusername':'الرجاء إدخال اسم المستخدم' ,
          'invalid':'اسم المستخدم وكلمة المرور غير صالحة', 
          'dontaccount':'ليس لديك حساب؟',  
           //labinvestigation
          'labinvestigation':'التحقيق المختبري',
          'selecttest':'حدد الاختبار',
           'pleaseselectpaymentmethod':'الرجاء تحديد طريقة الدفع',
           'pleaseenterremarks':"الرجاء إدخال الملاحظات",
               //terms&condition
            'disclaimer': 'تنصل',
          'consentTitle': 'موافقة',
            'consent':'باستخدام موقعنا وخدماتنا ومنتجاتنا، فإنك توافق بموجبه على سياسة الخصوصية الخاصة بنا وتوافق على شروطها. إذا كنت طبيبًا أو متخصصًا طبيًا تقوم بالتسجيل في هذا التطبيق، فمن خلال التسجيل في هذه الخدمة أو استخدامها، فإنك تؤكد بموجب هذا أن الاستخدام يقع على مسؤوليتك الخاصة، كما أنك تحرر وتوافق على إعفاء مقدمي الخدمة والمطورين والناشرين من المسؤولية عن العواقب الضارة. ، بما في ذلك على سبيل المثال لا الحصر المطالبات أو الإجراءات أو الإجراءات القانونية من قبل أطراف ثالثة أو فقدان أو خرق أي بيانات خاصة و/أو الأضرار التي لحقت نتيجة لذلك',
          'informationWeCollect': 'المعلومات التي نجمعها',
           'information1':'يستهدف نظامنا وتطبيقاتنا بشكل أساسي الرعاية الصحية والطبية. نقوم بجمع بعض المعلومات والأذونات الأخرى في تطبيقاتنا لتحسين تجربة المستخدم ووظائف التطبيق. تتم معالجة المعلومات التي نجمعها بشكل مؤقت، أي أنها تستخدم فقط لبدء بعض الخدمات أو الوظائف الموجودة داخل التطبيق ولا يتم استخدامها بعد إيقافها. تم ذكر بعض الأمور المهمة أدناه مع الإفصاح/أسباب التجميع البارزة',
          'information2':'الموقع: لإظهار الأطباء القريبين، يحتاج التطبيق إلى الحصول على هذا الإذن من المستخدم. من خلال تمكين الخدمات المستندة إلى الموقع على جهازك، فإنك توافق وتقر بأن (أ) بيانات الجهاز التي يتم جمعها منك ذات صلة مباشرة باستخدامك للتطبيق، (ب) قد نقدم خدمات تعتمد على الموقع تتعلق وتستند إلى موقعك الحالي في ذلك الوقت، و (ج) يجوز لنا استخدام أي معلومات تم جمعها فيما يتعلق بتوفير التطبيق. لإجراء مكالمات فيديو بين الطبيب والمريض. لإجراء مكالمات صوتية بين الطبيب والمريض (أ) يمكن للمستخدم/المريض تحميل صورة الملف الشخصي (ب) يمكن للمستخدم/المريض تحميل السجلات والملفات الصحية ليقوم الطبيب بفحصها (ج) يمكن للمستخدم/المريض تنزيل وعرض التقارير وما إلى ذلك.',
         'usageTitle': 'الاستخدام',
          'usage':'نحن نستخدم المعلومات التي نجمعها بطرق مختلفة، بما في ذلك: (أ) توفير خدماتنا ومنتجاتنا وتشغيلها وصيانتها (ب) فهم وتحليل كيفية استخدامك لخدماتنا ومنتجاتنا (ج) تطوير منتج جديد وميزات الخدمات و الوظيفة (د) التواصل معك، إما بشكل مباشر أو من خلال أحد شركائنا، بما في ذلك خدمة العملاء، لتزويدك بالتحديثات والمعلومات الأخرى المتعلقة بالموقع، ولأغراض تسويقية وترويجية (هـ) إرسال رسائل البريد الإلكتروني الخاصة بك (و) البحث عن الاحتيال ومنعه',
         'disclosureTitle': 'إفشاء',
           'disclosure':'يجوز لنا الكشف عن المعلومات الشخصية لأي شخص يقوم بتقديم خدمات التدقيق أو الخدمات القانونية أو التشغيلية أو غيرها من الخدمات لنا. سوف نستخدم المعلومات التي لا تحدد هوية الفرد لهذه الأنشطة كلما كان ذلك ممكنًا بشكل معقول. بموجب قانون CCPA، من بين حقوق أخرى، يحق للمستهلكين في كاليفورنيا أن يطلبوا من الشركة التي تجمع البيانات الشخصية الكشف عن فئات وأجزاء محددة من البيانات الشخصية التي جمعتها الشركة عن المستهلكين، ومطالبة الشركة بحذف أي بيانات شخصية، وعدم بيعها. البيانات الشخصية للمستهلكين. إذا قمت بتقديم طلب، لدينا شهر واحد للرد عليك. إذا كنت ترغب في ممارسة أي من هذه الحقوق، فيرجى الاتصال بنا عبر دعم العملاء بموجب حقوق حماية البيانات الخاصة باللائحة العامة لحماية البيانات (GDPR)، يحق لكل مستخدم طلب نسخ من بياناتك الشخصية. قد نفرض عليك رسومًا صغيرة مقابل الخدمة، والحق في طلب تصحيح أي معلومات تعتقد أنها غير دقيقة، والحق في طلب مسح بياناتك الشخصية، وتقييد معالجتها، والاعتراض على معالجتنا لبياناتك الشخصية، ونقل البيانات التي لقد قمنا بجمع البيانات إلى منظمة أخرى أو إليك مباشرة في ظل ظروف معينة. إذا قمت بتقديم طلب، لدينا شهر واحد للرد عليك. إذا كنت ترغب في ممارسة أي من هذه الحقوق، يرجى الاتصال بنا عبر دعم العملاء',
          'iHaveRead': 'لقد قرأت وفهمت',
          'theTermsAndCondition': 'الشروط والأحكام',
          'samplecollection':'جمع العينات',
          'call':'يتصل',
           'message':'رسالة'
        },
        "ur_PK": {
          //drawer
          'changepassword': 'تغيير كلمة المرور',
          'biometric': 'بائیو میٹرک',
          'languages': 'زبانیں',
          'privacyPolicy': 'رازداری اور پالیسی',
          'termsAndConditions': 'شرائط و ضوابط',
          'deleteAccount': 'کھاتہ مٹا دو',
          'logout': 'لاگ آوٹ',
          //Dashboard
          'goodmorning': "صبح بخیر",
          'goodEvening': 'شام بخیر',
          'goodNight': 'شب بخیر',
          'goodAfterNoon': 'دوپہر بخیر',
          'hi': 'ہیلو,',
          'todayappointments': 'آج کی ملاقاتیں',
          'appointmenthistory': 'تقرری کی تاریخ',
          'registrationordering': 'رجسٹریشن اور آرڈر',
          'comingsoon': 'جلد آرہا ہے',
          'registration': 'اندراج',
          'registerpatient': 'رجسٹرڈ مریض',
          //profile
          'profile': 'پروفائل',
          'vehiclenumber': 'گاڑی کا نمبر',
          'govid': 'سرکاری آئی ڈی',
          'contact': 'رابطہ نمبر',
          'dob': 'پیدائش کی تاریخ',
          'address': 'پتہ',
          //changepassword
          'welcometo': 'خوش آمدید',
          'helpful': 'Helpful.',
          'oldpassword': 'پرانا پاس ورڈ درج کریں',
          'newpassword': 'نیا پاس ورڈ درج کریں',
          'confirmpassword': 'نئے پاس ورڈ کی توثیق کریں',
          'submit': 'جمع کرائیں',
          'pleaseoldpassword': "براہ کرم پرانا پاس ورڈ درج کریں",
          'pleasenewpassword': 'براہ کرم نیا پاس ورڈ درج کریں',
          'pleaseconfirmpassword': 'براہ کرم تصدیقی پاس ورڈ درج کریں',
          'passwordnotmatch': 'پاس ورڈز مماثل نہیں ہیں',
          'passwordsuccess': 'پاس ورڈ کامیابی سے تبدیل کر دیا گیا',
          'passwordfailed': 'پرانا پاس ورڈ غلط ہے',
          //Notification
          'notification': 'اطلاع',
          //appointments
          'todayappointment': 'آج کی ملاقاتیں',
          'appointmenhistory': 'تقرری کی تاریخ',
          'from': 'سے',
          'to': 'تک',
          'test': 'ٹیسٹ   | ',
          'addres': 'پتہ   | ',
           'viewinformation':'معلومات دیکھیں',
           'startride':'سواری شروع کریں',
            'ridestatus':'سواری کی حالت',
          'wanttostart':'کیا آپ سواری شروع کرنا چاہتے ہیں؟',
          'yes':'جی ہاں',
          'no':'نہیں',
          'cancel':'منسوخ کریں',
          'arrived':'پہنچ گئے',
          'cancelride':'سواری منسوخ کریں',
          'remarks':'ریمارکس',
          'enterremarks':'ریمارکس درج کریں',
          'ok':'ٹھیک ہے',
          'arrivedatlocation':'کیا آپ مریض کے مقام پر پہنچ گئے ہیں؟',
          'checkin':'چیک ان',
          'paymentmethod':'ادائیگی کا طریقہ',
          'discount':'رعایت:',
          'paymentstatus':'ادائیگی کی حیثیت:',
          'totalamount':'کل رقم:',
          'percentage':"فیصد",
          'amount':'رقم',
          'samplecollected':'نمونہ جمع ',
          'inroutelab':'لیبارٹری کے راستے میں',
          'selectlab':'لیبارٹری کو منتخب کریں',
          'deliversample':'نمونہ فراہم کریں',
          'ridecompleted':'سواری مکمل',
          'thankyou':'شکریہ',
          'backhome':'واپس ڈیش بورڈ',
          'order':'ترتیب:',
          'ridestarted':'سواری کامیابی سے شروع ہوچکی ہے!',
          'pleaseselect':"براہ کرم لیب کو منتخب کریں",

          //Registration
          'registernow':'ابھی رجسٹر کریں',
          'fullname': 'پورا نام',
          'email': 'ای میل',
          'gender': 'جنس',
          'country': 'ملک',
          'state': 'صوبہ',
          'city': 'شہر',
          'relation': 'رشتہ',
          'nationalid': 'قومی شناخت  123-4567-8910111-2',
          'entername': 'اپنا پورا نام درج کریں',
          'entervalidno': 'براہ مہربانی ایک درست نمبر درج کریں',
          'enteremail': 'اپنا ای میل درج کریں',
          'selectgender': 'براہ کرم ایک جنس منتخب کریں',
          'enterid': 'شناختی نمبر درج کریں',
          'enteraddress': 'اپنا پتہ درج کریں',
          'vehicletype':'گاڑی کی قسم',
          'vehicleno':'گاڑی کا نمبر',
          'liscenceno':'لائسنس نمبر',
          'password':'پاس ورڈ',
          'repassword':'دوبارہ پاس ورڈ',
          'entervehicle':'گاڑی کا نمبر درج کریں',
          'enterliscenceno':'لائسنس نمبر درج کریں',
          'passnotmatch':'پاس ورڈ نہیں مل رہا!',
           'register':'رجسٹر کریں',
          'alreadyhaveacount':'پہلے سے اکاؤنٹ ہے؟',
          'signin':'سائن ان',
          'entervaliddata':'براہ کرم درست ڈیٹا درج کریں',
           //Login
          'login':'لاگ ان کریں',
          'username':'صارف نام',
          'enterusername':'براہ کرم اپنا صارف نام درج کریں',
          'invalid':' صارف نام اور پاس ورڈغلط ہیں', 
          'dontaccount':'کیا آپ کا اکاؤنٹ نہیں ہے؟', 
           //labinvestigation
          'labinvestigation':'لیبارٹری تحقیقات' ,
          'selecttest':'ٹیسٹ کا انتخاب کریں',
           'pleaseselectpaymentmethod':'براہ کرم ادائیگی کا طریقہ منتخب کریں',
           'pleaseenterremarks':"براہ کرم ریمارکس درج کریں",
            //terms&condition
            
          'disclaimer': 'ڈس کلیمر',
          'consentTitle': 'رضامندی',
            'consent':'ہماری ویب سائٹ، خدمات اور مصنوعات کا استعمال کرتے ہوئے، آپ اس کے ذریعے ہماری پرائیویسی پالیسی سے اتفاق کرتے ہیں اور اس کی شرائط سے اتفاق کرتے ہیں۔ اگر آپ اس درخواست کے لیے رجسٹر کرنے والے ڈاکٹر یا طبی پیشہ ور ہیں، تو اس سروس کے لیے رجسٹر ہو کر یا اس کا استعمال کرتے ہوئے، آپ اس بات کی تصدیق کرتے ہیں کہ استعمال آپ کے اپنے خطرے پر ہے، اور آپ سروس فراہم کرنے والوں، ڈویلپرز اور پبلشرز کو منفی ذمہ داری سے رہائی دیتے اور رضامند کرتے ہیں۔ نتائج جس میں فریقین ثالث کے دعووں، کارروائیوں یا قانونی کارروائیوں یا کسی بھی نجی ڈیٹا کے نقصان یا خلاف ورزی اور/یا اس کے نتیجے میں ہونے والے نقصانات سمیت لیکن ان تک محدود نہیں',
          'informationWeCollect': 'معلومات ہم جمع کرتے ہیں',
           'information1':'ہمارا سسٹم اور ایپلیکیشنز بنیادی طور پر صحت کی دیکھ بھال اور طبی دیکھ بھال کو نشانہ بناتے ہیں۔ ہم صارف کے تجربے اور ایپ کی فعالیت کو بہتر بنانے کے لیے اپنی ایپس میں کچھ دیگر معلومات اور اجازتیں جمع کرتے ہیں۔ ہم جو معلومات اکٹھا کرتے ہیں اس پر عارضی طور پر کارروائی کی جاتی ہے، یعنی یہ صرف ایپلی کیشن کے اندر مخصوص سروسز یا فنکشنز کو شروع کرنے کے لیے استعمال ہوتی ہے اور انہیں روکنے کے بعد استعمال نہیں کیا جاتا ہے۔ کچھ اہم معاملات کا ذکر ذیل میں نمایاں انکشاف/ جمع کی وجوہات کے ساتھ کیا گیا ہے',
          'information2':'مقام: قریبی ڈاکٹروں کو دکھانے کے لیے ایپ کو صارف سے یہ اجازت لینا ہوگی۔ اپنے آلے پر مقام پر مبنی خدمات کو فعال کر کے، آپ اس بات سے اتفاق کرتے ہیں اور تسلیم کرتے ہیں کہ (a) آپ سے جمع کردہ آلہ کا ڈیٹا براہ راست آپ کے ایپلیکیشن کے استعمال سے متعلق ہے، (b) ہم مقام پر مبنی خدمات فراہم کر سکتے ہیں جو ان سے متعلق ہیں اور اس پر مبنی ہیں۔ آپ کے اس وقت کے موجودہ مقام پر، اور (c) ) ہم درخواست فراہم کرنے کے سلسلے میں جمع کی گئی کوئی بھی معلومات استعمال کر سکتے ہیں۔ ڈاکٹر اور مریض کے درمیان ویڈیو کال کرنا۔ ڈاکٹر اور مریض کے درمیان صوتی کال کرنے کے لیے (a) صارف/مریض پروفائل تصویر اپ لوڈ کر سکتے ہیں (b) صارف/مریض ڈاکٹر کو چیک کرنے کے لیے ہیلتھ ریکارڈ اور فائلیں اپ لوڈ کر سکتے ہیں (c) صارف/مریض رپورٹس وغیرہ ڈاؤن لوڈ اور دیکھ سکتے ہیں۔',
         'usageTitle': 'استعمال',
          'usage':'ہم جو معلومات جمع کرتے ہیں اسے ہم مختلف طریقوں سے استعمال کرتے ہیں، بشمول: (a) ہماری سروسز اور پروڈکٹس کو فراہم کرنا، آپریٹ کرنا، اور برقرار رکھنا (b) یہ سمجھنا اور تجزیہ کرنا کہ آپ ہماری سروسز اور پروڈکٹس کو کس طرح استعمال کرتے ہیں (c) نئی مصنوعات اور خدمات کی خصوصیات اور فعالیت کو تیار کرنا ( d) آپ کے ساتھ براہ راست یا ہمارے کسی شراکت دار کے ذریعے، بشمول کسٹمر سروس، آپ کو سائٹ سے متعلق اپ ڈیٹس اور دیگر معلومات فراہم کرنے کے لیے، اور مارکیٹنگ اور پروموشنل مقاصد کے لیے (e) آپ کو ای میلز بھیجنا (f) پتہ لگانا اور دھوکہ دہی کی روک تھام',
          'disclosureTitle': 'انکشاف',
           'disclosure':'ہم کسی بھی شخص کو ذاتی معلومات کا انکشاف کر سکتے ہیں جو ہمیں آڈٹ، قانونی، آپریشنل یا دیگر خدمات فراہم کرتا ہے۔ جب بھی معقول حد تک ممکن ہو ہم معلومات استعمال کریں گے جو ان سرگرمیوں کے لیے کسی فرد کی شناخت نہیں کرتی ہے۔ CCPA کے تحت، دیگر حقوق کے علاوہ، کیلیفورنیا کے صارفین کو یہ حق حاصل ہے کہ وہ کاروبار جو ذاتی ڈیٹا اکٹھا کرتا ہے وہ ان زمروں اور ذاتی ڈیٹا کے مخصوص ٹکڑوں کو ظاہر کرے جو کسی کاروبار نے صارفین کے بارے میں جمع کیے ہیں، اور یہ درخواست کرنے کے لیے کہ کاروبار کسی بھی ذاتی ڈیٹا کو حذف کر دے۔ اسے فروخت کرنے کے لئے نہیں. صارفین کا ذاتی ڈیٹا۔ اگر آپ کوئی درخواست جمع کراتے ہیں، تو ہمارے پاس آپ کا جواب دینے کے لیے ایک مہینہ ہے۔ اگر آپ ان حقوق میں سے کسی کو استعمال کرنا چاہتے ہیں، تو براہ کرم ہم سے کسٹمر سپورٹ کے ذریعے رابطہ کریں اپنے ڈیٹا پروٹیکشن کے حقوق کے تحت جنرل ڈیٹا پروٹیکشن ریگولیشن (GDPR) کے تحت، ہر صارف کو آپ کے ذاتی ڈیٹا کی کاپیوں کی درخواست کرنے کا حق ہے۔ ہم آپ سے سروس کے لیے ایک چھوٹی سی فیس وصول کر سکتے ہیں، یہ درخواست کرنے کا حق کہ ہم کسی بھی ایسی معلومات کو درست کریں جو آپ کے خیال میں غلط ہے، یہ درخواست کرنے کا حق کہ ہم آپ کے ذاتی ڈیٹا کو مٹا دیں، اس کی کارروائی کو محدود کریں، آپ کے ذاتی ڈیٹا کی ہماری پروسیسنگ پر اعتراض کریں، ہم نے جو ڈیٹا اکٹھا کیا ہے اسے کسی دوسری تنظیم یا براہ راست آپ کو مخصوص حالات میں منتقل کریں۔ اگر آپ کوئی درخواست جمع کراتے ہیں، تو ہمارے پاس آپ کا جواب دینے کے لیے ایک مہینہ ہے۔ اگر آپ ان حقوق میں سے کسی کو استعمال کرنا چاہتے ہیں، تو براہ کرم کسٹمر سپورٹ کے ذریعے ہم سے رابطہ کریں۔',
          'iHaveRead': 'میں نے پڑھا اور سمجھا',
          'theTermsAndCondition': 'شرائط و ضوابط',
          'labqeue':'لیب کی قطار',
          'samplecollection':'نمونہ جمع',
          'call':'کال',
           'message':'پیغام'
         
        
        }
      };
}
// "welcometo": "مرحبا بك في",
//           "takecareof": "اعتني ب ",
//           "yourhealth": "صحتك!",
//           "with": "مع",
//           'goodmorning': "صباح الخير",
//           'goodEvening': 'مساء الخير',
//           'goodNight': 'طاب مساؤك',
//           'goodAfterNoon': 'مساء الخير',
//           'onlineOffline': 'متصل غير متصل',
//           'consultations': 'استشارات',
//           'booknow': 'احجز الآن',
//           'selectservices': 'حدد الخدمات',
//           'homeSample': 'عينة المنزل',
//           'imageBooking': 'حجز الصور',
//           'doctorConsultation': 'استشارة الطبيب',
//           'reports': 'التقارير',
//           'healthSummary': 'ملخص الصحة',
//           'healthAnalysis': 'التحليل الصحي',
//           'todayAvailable': 'متوفر اليوم',
//           'generalConsultation': 'الاستشارة العامة',
//           'getAppointment': 'احصل على موعد',
//           'home': 'بيت',
//           'profile': 'حساب تعريفي',
//           'schedule': 'جدول',
//           'help': 'يساعد',
//           'history': 'تاريخ',
//           'familyMembers': 'أفراد الأسرة',
//           'location': 'موقع',
//           'wallet': 'محفظة',
//           'packages': 'الحزم',
//           'forgotPassword': 'هل نسيت كلمة السر',
//           'biometric': 'بصمات',
//           'privacyPolicy': 'سياسة الخصوصية',
//           'termsAndConditions': 'البنود و الظروف',
//           'logout': 'تسجيل خروج',
//           'labInvestions': 'التحقيقات المخبرية',
//           'selectTest': 'حدد اختبار',
//           'description': 'وصف',
//           'address': 'عنوان',
//           'paymentMethod': 'طريقة الدفع او السداد',
//           'prescribedBy': 'المنصوص عليها',
//           'self': 'الذات',
//           'doctor': 'طبيب',
//           'outdoorDoctor': 'طبيب خارجي',
//           'select Doctor': 'اختر الطبيب',
//           'summary': 'ملخص',
//           'datehour': 'التاريخ والساعة',
//           'package': 'طَرد',
//           'test': 'امتحان',
//           'price': 'سعر',
//           'grandTotal': 'المجموع الإجمالي',
//           'appointmentConfirm': 'موعد الكتاب',
//           'attachPrescription': 'إرفاق وصفة طبية',
//           'login': 'تسجيل الدخول',
//           'Login': 'تسجيل الدخول',
//           'donthaveanAccount': 'لا تملك حساب',
//           'register': 'يسجل',
//           'registerNow': 'سجل الان',
//           'fullName': 'الاسم الكامل',
//           'yourMobNumber': 'رقم هاتفك',
//           'email': 'بريد إلكتروني',
//           'dateOfBirth': 'تاريخ الميلاد',
//           'gender': 'جنس',
//           'password': 'كلمة المرور',
//           'retypePassword': 'أعد إدخال كلمة السر',
//           'country': 'دولة',
//           'state': 'ولاية',
//           'city': 'مدينة',
//           'street': 'شارع',
//           'alreadyHaveAnAccount': 'هل لديك حساب؟',
//           'signin': 'تسجيل الدخول',
//           'registered': 'مسجل',
//           'registrationCompleted': 'تم التسجيل بنجاح',
//           'ok': 'نعم',
//           'payfromYourWallet': 'ادفع من محفظتك',
//           'payOnline': 'ادفع عبر الإنترنت',
//           'payAtClinic': 'الدفع في العيادة',
//           'congratulations': 'تهانينا',
//           'myAppointments': 'مواعيدي',
//           'bookyourAppointments': 'احجز موعدك',
//           'searchDoctor': 'البحث عن الأطباء',
//           'patients': "مرضى",
//           'yearExperience': 'سنوات من الخبرة',
//           'rating': 'التقييمات',
//           'reviews': 'التعليقات',
//           'descriptions': 'الأوصاف',
//           'workingTime': 'وقت العمل',
//           'online&Clinic': 'رسوم الاستشارة عبر الإنترنت والعيادة',
//           'bookAppointment': 'موعد الكتاب',
//           'welcomeTo': 'مرحبا بك في',
//           'username': 'اسم المستخدم',
//           'oopsFailed': 'عفوًا، فشل',
//           'appointmentFailed': 'فشل الموعد',
//           'checkInternet': 'الرجاء التحقق من اتصالك بالإنترنت وحاول مرة أخرى',
//           'appointmentBooked': 'تم حجز الموعد بنجاح',
//           'viewAppointment': 'عرض الموعد',
//           'cancel': 'يلغي',
//           'glucose': "الجلوكوز",
//           'bloodPressure': 'ضغط الدم',
//           'measurements': 'قياسات',
//           'connect': 'يتصل',
//           'pulse': 'نبض',
//           'temperature': 'درجة حرارة',
//           'labTestResult': 'نتيجة الاختبار المعملي',
//           'status': 'حالة',
//           'pending': 'قيد الانتظار',
//           'allergies': 'الحساسية',
//           'addGlucose': 'أضف الجلوكوز',
//           'normal': 'طبيعي',
//           'fasting': 'صيام',
//           'values': 'قيم',
//           'condtition': 'حالة',
//           'saveRecord': 'حفظ السجل',
//           'calculate': 'احسب',
//           'bmiCalculator': 'حاسبة مؤشر كتلة الجسم',
//           'BMI': 'مؤشر كتلة الجسم',
//           'glucoseLevelMonitor': 'مراقب مستوى الجلوكوز',
//           'enterValue': 'أدخل القيمة',
//           'collectLocationData':
//               'يقوم طبيب البيت لرعاية المرضى بجمع بيانات الموقع لتمكين خدمات أخذ العينات المنزلية حتى عندما تكون مغلقة أو غير مستخدمة',
//           'permissions': 'الأذونات',
//           'deleteAccount': 'حذف الحساب',
//           'languages': "لغة",
//           'identityNumber': 'رقم الهوية',
//           'signup': 'اشتراك',
//           'bpm': 'نبضة في الدقيقة',
//           'date': 'تاريخ',
//           'time': 'وقت',
//           'searchForSpecialities': 'البحث عن القسم',
//           'consultNow': 'استشر عبر الإنترنت',
//           'specialists': 'المتخصصين',
//           'upcomingAppointments': 'المواعيد القادمة',
//           'dateAndTime': 'التاريخ و الوقت',
//           'reschedule': 'إعادة جدولة',
//           'onlineConsultation': 'التشاور عبر الإنترنت',
//           'information1':
//               'يستهدف نظامنا وتطبيقاتنا بشكل أساسي الرعاية الصحية والطبية. نقوم بجمع بعض المعلومات والأذونات الأخرى في تطبيقاتنا لتحسين تجربة المستخدم ووظائف التطبيق. تتم معالجة المعلومات التي نجمعها بشكل مؤقت، أي أنها تستخدم فقط لبدء بعض الخدمات أو الوظائف الموجودة داخل التطبيق ولا يتم استخدامها بعد إيقافها. تم ذكر بعض الأمور المهمة أدناه مع الإفصاح/أسباب التجميع البارزة',
//           'information2':
//               'الموقع: لإظهار الأطباء القريبين، يحتاج التطبيق إلى الحصول على هذا الإذن من المستخدم. من خلال تمكين الخدمات المستندة إلى الموقع على جهازك، فإنك توافق وتقر بأن (أ) بيانات الجهاز التي يتم جمعها منك ذات صلة مباشرة باستخدامك للتطبيق، (ب) قد نقدم خدمات تعتمد على الموقع تتعلق وتستند إلى موقعك الحالي في ذلك الوقت، و (ج) يجوز لنا استخدام أي معلومات تم جمعها فيما يتعلق بتوفير التطبيق. لإجراء مكالمات فيديو بين الطبيب والمريض. لإجراء مكالمات صوتية بين الطبيب والمريض (أ) يمكن للمستخدم/المريض تحميل صورة الملف الشخصي (ب) يمكن للمستخدم/المريض تحميل السجلات والملفات الصحية ليقوم الطبيب بفحصها (ج) يمكن للمستخدم/المريض تنزيل وعرض التقارير وما إلى ذلك.',
//           'usage':
//               'نحن نستخدم المعلومات التي نجمعها بطرق مختلفة، بما في ذلك: (أ) توفير خدماتنا ومنتجاتنا وتشغيلها وصيانتها (ب) فهم وتحليل كيفية استخدامك لخدماتنا ومنتجاتنا (ج) تطوير منتج جديد وميزات الخدمات و الوظيفة (د) التواصل معك، إما بشكل مباشر أو من خلال أحد شركائنا، بما في ذلك خدمة العملاء، لتزويدك بالتحديثات والمعلومات الأخرى المتعلقة بالموقع، ولأغراض تسويقية وترويجية (هـ) إرسال رسائل البريد الإلكتروني الخاصة بك (و) البحث عن الاحتيال ومنعه',
//           'disclosure':
//               'يجوز لنا الكشف عن المعلومات الشخصية لأي شخص يقوم بتقديم خدمات التدقيق أو الخدمات القانونية أو التشغيلية أو غيرها من الخدمات لنا. سوف نستخدم المعلومات التي لا تحدد هوية الفرد لهذه الأنشطة كلما كان ذلك ممكنًا بشكل معقول. بموجب قانون CCPA، من بين حقوق أخرى، يحق للمستهلكين في كاليفورنيا أن يطلبوا من الشركة التي تجمع البيانات الشخصية الكشف عن فئات وأجزاء محددة من البيانات الشخصية التي جمعتها الشركة عن المستهلكين، ومطالبة الشركة بحذف أي بيانات شخصية، وعدم بيعها. البيانات الشخصية للمستهلكين. إذا قمت بتقديم طلب، لدينا شهر واحد للرد عليك. إذا كنت ترغب في ممارسة أي من هذه الحقوق، فيرجى الاتصال بنا عبر دعم العملاء بموجب حقوق حماية البيانات الخاصة باللائحة العامة لحماية البيانات (GDPR)، يحق لكل مستخدم طلب نسخ من بياناتك الشخصية. قد نفرض عليك رسومًا صغيرة مقابل الخدمة، والحق في طلب تصحيح أي معلومات تعتقد أنها غير دقيقة، والحق في طلب مسح بياناتك الشخصية، وتقييد معالجتها، والاعتراض على معالجتنا لبياناتك الشخصية، ونقل البيانات التي لقد قمنا بجمع البيانات إلى منظمة أخرى أو إليك مباشرة في ظل ظروف معينة. إذا قمت بتقديم طلب، لدينا شهر واحد للرد عليك. إذا كنت ترغب في ممارسة أي من هذه الحقوق، يرجى الاتصال بنا عبر دعم العملاء',
//           'consent':
//               'باستخدام موقعنا وخدماتنا ومنتجاتنا، فإنك توافق بموجبه على سياسة الخصوصية الخاصة بنا وتوافق على شروطها. إذا كنت طبيبًا أو متخصصًا طبيًا تقوم بالتسجيل في هذا التطبيق، فمن خلال التسجيل في هذه الخدمة أو استخدامها، فإنك تؤكد بموجب هذا أن الاستخدام يقع على مسؤوليتك الخاصة، كما أنك تحرر وتوافق على إعفاء مقدمي الخدمة والمطورين والناشرين من المسؤولية عن العواقب الضارة. ، بما في ذلك على سبيل المثال لا الحصر المطالبات أو الإجراءات أو الإجراءات القانونية من قبل أطراف ثالثة أو فقدان أو خرق أي بيانات خاصة و/أو الأضرار التي لحقت نتيجة لذلك',
//           'consentTitle': 'موافقة',
//           'usageTitle': 'الاستخدام',
//           'disclosureTitle': 'إفشاء',
//           'informationWeCollect': 'المعلومات التي نجمعها',
//           'iHaveRead': 'لقد قرأت وفهمت',
//           'theTermsAndCondition': 'الشروط والأحكام',
//           'accept': 'يقبل',
//           'decline': 'انخفاض',
//           'height': 'ارتفاع',
//           'weight': 'وزن',
//           'add': 'يضيف',
//           'servicesHome': 'الخدمات (المنزلية)',
//           'teleConsultation': 'الاستشارة عن بعد',
//           'diagnostics': 'التشخيص',
//           'physio': 'فيزيائي',
//           'nursing': 'التمريض',
//           'caregiver': 'الراعي',
//           'respiratoryTherapy': 'العلاج التنفسي',
//           'dietitian': 'اخصائي تغذيه',
//           'serviceSelected': 'الخدمة مختارة',
//           'agree': 'يوافق',
//           'appointmentNotes': 'ملاحظات التعيين',
//           'deny': 'ينكر',
//           'search': 'يبحث',
//           'homeVisit': 'زيارة منزلية',
//           'online': 'متصل',
//           'subTotal': 'المجموع الفرعي',
//           'minFee': 'الحد الأدنى للرسوم',
//           'doctorSchedule': 'جدول الطبيب',
//           'fee': 'مصاريف',
//           'charges': 'رسوم',
//           'selectAddress': 'حدد العنوان',
//           'selectLocation': 'اختر موقعا',
//           'goodMorning': 'صباح الخير',
//           'token': 'رمز مميز',
//           'ecg': 'تخطيط القلب الكهربي',
//           'selectLanguage': 'اختار اللغة',
//           'hour': 'ساعة',
//           'homeService': 'خدمة الرعاية المنزلية',
//           'labInvestigationBooking': 'حجز الفحوصات المخبرية',
//           'experience': 'خبرة',
//           'paying': 'الدفع',
//           'serviceBooked': 'تم حجز الخدمة بنجاح',
//           'appointmentSuccessful': "تم حجز الموعد بنجاح. سوف تتلقى إخطارا",
//           'failedAppointment':
//               'Appointment failed please check your internet connection then try again.',
//           'favorites': 'المفضلة',
//           'noFavorites': 'لم تتم إضافة أي الأطباء المفضلين',
//           'contact': 'رقم الاتصال',
//           'province/state': 'المقاطعة/الولاية',
//           'editProfile': 'تعديل الملف الشخصي',
//           'mobNumber': 'رقم الهاتف المحمول',
//           'update': 'تحديث',
//           'healthanalysis': 'تحليل الصحة',
//           'herearesomehealth': 'فيما يلي بعض الحقائق الصحية حول',
//           'men': 'رجال',
//           'In': 'في',
//           'dubai': 'دبي الامارات العربية المتحدة',
//           'doctorName': 'اسم الطبيب',
//           'careGiver': 'الراعي',
//           'condition': 'حالة',
//           'disclaimer': 'تنصل',
//           'services': 'خدمات',
//           "manageYourHealth": 'إدارة صحتك معنا',
//           'go': 'يذهب',
//           'imaging': 'حجز التصوير',
//           'caretocure': 'من الرعاية إلى العلاج',
//           'specialities': 'التخصصات',
//           'consultatclinic': 'استشارة في العيادة',
//           'forgotpassword': 'كلمة سر منسية',
//           'ithappens':
//               'إذا حدث ذلك، يرجى إدخال البريد الإلكتروني المرتبط بحسابك',
//           'createpassword': 'إنشاء كلمة مرور جديدة',
//           'kindlyenter': 'يرجى إدخال كلمة مرور فريدة',
//           'oldpaasword': 'كلمة المرور القديمة',
//           'confirmpassword': 'تأكيد كلمة المرور',
         
//           'imagingbooking': 'حجز التصوير',
//           'imagingTitle': 'التصوير',
//           'completed': 'مكتمل',
//           'upcoming': 'القادمة',
//           'cancelled': 'ألغيت',
//           'noDataFound': 'لاتوجد بيانات!',
//           'service': 'خدمة',
//           'homeServices': 'خدمات منزلية',
//           'changePassword': 'تغيير كلمة المرور',
//           'modeOfPayment': 'طريقة الدفع'
